Gopkg.lock, Gopkg.toml, cmd/rhpam-operator/main.go, deploy/trial-environment.yaml
[KIECLOUD-6] Set operator-sdk version to v0.0.6 for vendoring & stability
=> [KIECLOUD-6] set operator-sdk version to v0.0.6 for vendoring & stability

README.md, internal/app/handler/handler_test.go, internal/pkg/defaults/.packr/packr.go, internal/pkg/defaults/defaults.go, internal/pkg/defaults/defaults_test.go, internal/pkg/kieserver/objects.go, internal/pkg/rhpamcentr/objects.go, internal/pkg/shared/utils.go, tmp/build/build.sh
[KIECLOUD-17] Standardize go format and generate
Automate `go fmt` & `go generate` for the code base at build time. Ensures differing formatting from IDE's aren't included in commit's.
Added commands to `tmp/build/build.sh` file which is executed during an `operator-sdk build quay.io/kiegroup/kie-cloud-operator`
=> [KIECLOUD-17] fmt & generate automation

Gopkg.lock, config/common/server.yaml, config/envs/production-lite.yaml, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/merge.go, pkg/controller/kieapp/defaults/merge_test.go
The provided merge.go is not 100% complete, but goes a long way towards merging OpenShift objects. The production-lite.yaml starts validating this approach by taking out just a small subset of its content and moving them to server.yaml, with merge_test.go validating the result.
The defaults.go class has undergone minimal refactor to allow the use of envTemplate logic without breaking current usage.
=> [KIECLOUD-47] First few steps towards a comprehensive merge framework

pkg/apis/app/v1/kieapp_types.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go, pkg/controller/kieapp/test/mock_service.go
Allow unit testing to extend beyond reading environments from files.
The new PlatformService represents some of the actions not available outside of Kubernetes, that are now mocked up by the test.MockPlatformService for use in unit tests
=> [KIECLOUD-65] Allow unit testing for environment processing

cmd/manager/main.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/defaults/merge.go, pkg/controller/kieapp/defaults/merge_test.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go, pkg/controller/kieapp/kieserver/objects.go, pkg/controller/kieapp/rhpamcentr/objects.go, pkg/controller/kieapp/shared/utils.go
- reorder args sent to logger for most log items
Error, Info, Warn, & Debug all use fmt.Sprint to construct and log a message.
https://godoc.org/go.uber.org/zap#SugaredLogger.Error
=> [KIECLOUD-78] Change most log lines for SugaredLogger format

pkg/controller/kieapp/kieapp_controller.go
When the image stream is created locally, the local namespace should be  returned to be set on the object. Also refactored function to be more clear.
=> [KIECLOUD-86] Use local namespace for objects after creating image streams

config/envs/production-immutable.yaml, deploy/crs/kieapp_production-immutable.yaml, pkg/apis/app/v1/kieapp_types.go, pkg/apis/app/v1/zz_generated.deepcopy.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go
- Schema change to allow an array of KieAppBuildObject entries, where each indicates a KIE server deployment
- Template change to populate each iteration of KIE server template individually based on provided build config details
- Removing KIE_SERVER_CONTROLLER paramenters to allow connection to monitoring console
=> [KIECLOUD-88] Allow immutable environment with multiple KIE servers

config/envs/authoring-ha.yaml, deploy/role.yaml
- unset `RHPAM_XA_CONNECTION_PROPERTY_URL` env var, similarly done in other envs.
- add permission for buildconfigs to operator role
=> [KIECLOUD-90] authoring-ha db env & bc role fixes

deploy/crds/kieapp_crd.yaml
Commenting out most conditional required elements to allow things to work with OCP 3.11, to be revisited later
It appears that in 3.11, the validation looks one level deeper than what is provided in the CR, resulting in a lot of false positives
=> [KIECLOUD-91] Follow-up PR for CRD validation

OWNERS
Fix https://issues.jboss.org/browse/KIECLOUD-93
Adding OWNERS file required by the ci tool ([Prow approve plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/approve/approvers))
=> [KIECLOUD-93] Add OWNERS file

Gopkg.lock, cmd/manager/main.go, pkg/controller/kieapp/constants/constants.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/watch.go
- initialize ConfigMaps on startup
- only when running with a deployment
- allow for proper CR deployment in dev env w/o configmaps
- add versioned annotation
- set ownerref on them for proper cleanup when the operator is deleted
- if user makes changes to default CMs, take versioned backup and remove ownerref so it remains
- improve general reconciliation
=> [KIECLOUD-53] ConfigMap & reconcile improvements

README.md, pkg/controller/kieapp/kieapp_controller.go
- add operator version annotation to deployed cr's
- use "Local" reference policy in imagestream tags
- fix ineffectual assignment
=> [KIECLOUD-106] operator version annotation in CR & set image reference policy

config/common.yaml, config/envs/rhdm-authoring-ha.yaml, config/envs/rhdm-optaweb-trial.yaml, config/envs/rhdm-production-immutable.yaml, config/envs/rhdm-trial.yaml, config/envs/rhpam-authoring-ha.yaml, config/envs/rhpam-authoring.yaml, config/envs/rhpam-production-immutable.yaml, config/envs/rhpam-production.yaml, config/envs/rhpam-trial.yaml, pkg/controller/kieapp/kieapp_controller.go
the rhpam and rhdm templates use an "application" label for further identification.
=> [KIECLOUD-125] add application label to objects

pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go
defaults to 1 kieserver in CR when neither Server or Servers objects are set.
e.g.
```yaml
objects:
console:
resources: {}
server:
deployments: 1
server:
resources: {}
smartrouter:
resources: {}
```
=> [KIECLOUD-128] set default server object in CR

container.yaml, hack/go-build.sh, image.yaml, modules/business-automation-operator/install, modules/kie-cloud-operator/install, modules/kie-cloud-operator/module.yaml
With these changes, we see successful builds in OSBS.
Current build method relies on a preexisting tarball of operator binary being available for download via GitHub release. e.g. - https://github.com/kiegroup/kie-cloud-operator/releases/tag/v0.1
=> [KIECLOUD-115] osbs changes

Makefile, README.md, hack/go-build.sh, image.yaml
- add rhel-release option to Makefile
- uses release candidate build flag `--build-osbs-release` for proper tagging.
- additional content_set necessary for minimal image builds.
=> [KIECLOUD-133] add cekit flag so image properly tagged after build

deploy/catalog_resources/community/kiecloud-operator.v1.0.0.clusterserviceversion.yaml, deploy/catalog_resources/community/kiecloud.package.yaml, deploy/catalog_resources/kiecloud.package.yaml, deploy/catalog_resources/redhat/businessautomation-operator.v1.0.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/businessautomation.package.yaml, deploy/operator.yaml, hack/catalog-redhat.sh, hack/go-build.sh, image.yaml, version/version.go
- changed version to 1.0
- added CatalogSource for supported Operator deployment
- can be used in OLM by executing `./hack/catalog-redhat.sh`
- changed RH image name to `rhpam73-operator`
=> [KIECLOUD-133] version and additional osbs tweaks

hack/catalog-redhat.sh
Logic added so bundle file only generates if the necessary subdir exists. This is important as this script will likely also be executed by end users outside of this github branch.
=> bundle shell script mod

deploy/examples/common_config.yaml, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go
also resolves issues w/ common-config example.
=> [KIECLOUD-139] use commonConfig.applicationName for object naming

pkg/controller/kieapp/defaults/defaults.go
move server sets without names to the end of the slice so that unique KieNames with correct indexing can be generated, avoiding potential for conflicts.
=> [KIECLOUD-142] sort servers

config/common.yaml, deploy/crds/kieapp.crd.yaml, deploy/examples/immutable_deployment.yaml, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/kieapp_controller.go
Fix https://issues.jboss.org/browse/KIECLOUD-116
* Added some unit tests
* Missing Buildconfig reconciliation
* contextDir should not be mandatory
* use podIP as kieServerLocation. Shouldn't use routes
=> [KIECLOUD-116] Fix CRD and S2I reconciliation

config/dbs/h2.yaml, config/envs/rhdm-authoring.yaml, config/envs/rhdm-trial.yaml, config/envs/rhpam-authoring.yaml, config/envs/rhpam-trial.yaml, deploy/crs/kieapp_rhdm_production-immutable.yaml, pkg/controller/kieapp/constants/constants.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/defaults/merge_test.go
Fix https://issues.jboss.org/browse/KIECLOUD-149
* Remove h2 configuration as it is already the default one
* Remove ping service and env vars for rhpamcentr in trial environments
* Remove kie_server_port and protocol env vars
* Use podIP as KIE_SERVER_HOST also for trial envs
* Trial server replicas set to 1
=> [KIECLOUD-149] Fix trial environments

config/common.yaml, config/dbs/h2.yaml, config/envs/rhdm-trial.yaml, config/envs/rhpam-trial.yaml, pkg/controller/kieapp/defaults/defaults_test.go
- kie servers which are using a persisted h2 db require the `Recreate` DC strategy, otherwise the following errors are thrown and rollout never successfully finishes.
```shell
18:54:10,431 ERROR [org.jboss.jca.core.tx.jbossts.XAResourceRecoveryImpl] (Periodic Recovery) IJ000906: Error during crash recovery: java:/jboss/datasources/rhpam_EJBTimer (IJ031084: Unable to create connection): javax.resource.ResourceException: IJ031084: Unable to create connection
at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.getXAManagedConnection(XAManagedConnectionFactory.java:531)
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-193]
at …
```
=> [RHPAM-1952] resolve kie server sticky session issue

.gitignore, hack/go-build.sh, image.yaml, pkg/controller/kieapp/constants/constants.go, version/version.go
- improved handling of source code artifact
bring up master to 1.0.1 / 7.3.1 to match `1.0.x` branch before versioning for 1.1 / 7.4 in master.
i should have done this to master first originally and cherry-picked to 1.0.x ... will do next time.
=> increment version 1.0.1 for 7.3.1

config/common.yaml, deploy/crds/kieapp.crd.yaml, deploy/examples/openshift_startup.yaml, deploy/examples/server_config.yaml, pkg/apis/app/v1/kieapp_types.go, pkg/controller/kieapp/constants/constants.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/watch.go
/assign @bmozaffa @rhtevan
- still not defaulting to OpenShiftStartupStrategy, but include an example that enables it
- adds ability to set server id within CR spec
- changes appropriate server ConfigMap label to "DETACHED" when the operator detects a server's replicas set to zero
=> [JBPM-8150] Allow users to change Kie server id in Deployment config

deploy/catalog_resources/courier/kiecloud-operatorsource.yaml, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go
Cherry-pick from master
KIE Server should also use any provided commonConfig imageTag, as console and smart router do
=> [KIECLOUD-190] KIE Server needs to respect configured imageTag

deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.0.1/businessautomation-operator.1.0.1.clusterserviceversion.yaml, deploy/catalog_resources/redhat/catalog-source.yaml
Operator CSV installModes should have SingleNamespace support set to true
=> [KIECLOUD-193] Update CSV installModes

config/envs/rhdm-authoring-ha.yaml, config/envs/rhpam-authoring-ha.yaml, config/jms/activemq-jms-config.yaml
https://issues.jboss.org/browse/KIECLOUD-221
[KIECLOUD-221] upgrade datagrid and amq broker versions
=> [KIECLOUD-221] upgrade datagrid and amq broker versions

build/Dockerfile, build/bin/user_setup, image.yaml, modules/kie-cloud-operator/install
- USER_NAME and USER_UID vars are unecessary
- HOME dir always already exists because build occurs as root
- this simplifies a bit and bring the 2 builds closer (docker & osbs)
/assign @bmozaffa @ruromero 
=> user_setup script fixes

pkg/controller/kieapp/logs/logs.go
new log entry:
```
{"level":"info","ts":"2019-05-29T19:38:03.17433Z","logger":"cmd","msg":"Starting the Operator."}
```
/assign @sutaakar @errantepiphany 
=> [KIECLOUD-198] change timestamp to something more readable

config/dbs/mysql.yaml, config/dbs/postgresql.yaml
[RHPAM-2226] Validation subelement is missing for datasources
Validation subelement is missing for datasources
=> [RHPAM-2226] Validation subelement is missing for datasources

config/envs/rhdm-trial.yaml, config/envs/rhpam-trial.yaml
Fix https://issues.jboss.org/browse/KIECLOUD-149
* Disable JGROUPS for DecisionManager and BusinessCentral in trial environments
=> [KIECLOUD-149] Fix rhdm/rhpam trial environments

config/jms/activemq-jms-config.yaml, deploy/crds/kieapp.crd.yaml, deploy/crs/kieapp_rhdm_production-immutable-jms.yaml, deploy/crs/kieapp_rhpam_production-immutable-jms.yaml, pkg/apis/app/v1/kieapp_types.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go
It doesn't make sense to repeat `KieServerJms` in the struct's attributes as it is obvious they are KieServer.Jms attributes
=> Rename JMS fields

config/7.5.0/envs/rhdm-authoring-ha.yaml, config/7.5.0/envs/rhdm-authoring.yaml, config/7.5.0/envs/rhdm-trial.yaml, config/7.5.0/envs/rhpam-authoring-ha.yaml, config/7.5.0/envs/rhpam-authoring.yaml, config/7.5.0/envs/rhpam-trial.yaml, pkg/controller/kieapp/defaults/defaults_test.go
See:
https://issues.jboss.org/browse/KIECLOUD-160
```
git clone https://rhpam-authoring-rhpamcentr-kie-operator.apps.rhba-zanini2.openshift-aws.rhocf-dev.com:443/git/MySpace/example-Course_Scheduling
Cloning into 'example-Course_Scheduling'...
Username for 'https://rhpam-authoring-rhpamcentr-kie-operator.apps.rhba-zanini2.openshift-aws.rhocf-dev.com:443': adminUser
Password for 'https://adminUser@rhpam-authoring-rhpamcentr-kie-operator.apps.rhba-zanini2.openshift-aws.rhocf-dev.com:443': 
remote: Counting objects: 69, done
remote: Finding sources: 100% (69/69)
remote: Getting sizes: 100% (65/65)
remote: Compressing objects: 100% (69535/69535)
remote: Total 69 (delta 38), reused 0 (delta 0)
Unpacking objects: 100% (69/69), done.
```
Successfully cloned a project via HTTPS deploying Kie …
=> [KIECLOUD-160] Removing unnecessary git ports from containers

config/7.5.0/common.yaml
[RHPAM-2282] Changes in users and roles made by Business central are not persisted
https://issues.jboss.org/browse/RHPAM-2282
=> [RHPAM-2282] Changes in users and roles made by Business central are not persisted

Gopkg.lock, Gopkg.toml, deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml, deploy/examples/v2/minor_upgrade.yaml, pkg/apis/app/v2/conversion.go, pkg/apis/app/v2/conversion_test.go, pkg/controller/kieapp/constants/constants.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/defaults/upgrade.go, pkg/controller/kieapp/defaults/upgrade_test.go, pkg/controller/kieapp/kieapp_controller.go, vendor/github.com/google/go-cmp/cmp/cmpopts/util_test.go, vendor/github.com/google/go-cmp/cmp/compare_test.go, vendor/github.com/google/go-cmp/cmp/internal/value/sort.go, vendor/github.com/google/go-cmp/cmp/internal/value/zero.go, vendor/github.com/google/go-cmp/cmp/internal/value/zero_test.go, vendor/github.com/google/go-cmp/cmp/report_compare.go, vendor/github.com/google/go-cmp/cmp/report_reflect.go, vendor/github.com/google/go-cmp/cmp/report_slices.go, vendor/github.com/google/go-cmp/cmp/report_text.go
also addresses -
https://issues.jboss.org/browse/KIECLOUD-287
https://issues.jboss.org/browse/KIECLOUD-288
Added initial CRD api conversion code. Can't fully enable until `CustomResourceWebhookConversion` feature is out of OpenShift Tech Preview.
=> [KIECLOUD-285] Enable basic upgrade support

Gopkg.lock, Gopkg.toml, pkg/apis/app/v1/kieapp_types.go, pkg/apis/app/v2/kieapp_types.go, pkg/controller/kieapp/deploy_ui.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go, pkg/controller/kieapp/shared/utils.go, pkg/controller/kieapp/test/mock_service.go, pkg/controller/kube_service.go, vendor/github.com/RHsyseng/operator-utils/Gopkg.lock, vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults_test.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/map.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/test/external_test.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/test/utils_test.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/types.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/utils.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/test/utils.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/test/utils_test.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/types.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/types_test.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/hooks/update_hooks.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer.go, vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer_test.go
Use new operator-utils functionality to do a full reconcile of requested and existing resources
Remaining items:
- Pass unit tests
- Refactor route hostname so update happens automatically as hostname is set
=> Full reconcile of resources using shared library

deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml, deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
Given the 1.1.1 / 7.4.1 release didn't get RollingUpdate changes which allows for CSV upgrades... we can't start allowing csv upgrades until the next release. In fact, we don't want the user to even attempt an upgrade as OLM will throw errors and just stall in progress.
=> Reserve CSV upgrades for 1.2.1 / 7.5.1 release

config/7.5.0/envs/rhdm-authoring-ha.yaml, config/7.5.0/envs/rhpam-authoring-ha.yaml, pkg/controller/kieapp/constants/constants.go
[RHPAM-2354] OutOfMemoryError on Datagrid cause issues on project import indexing
https://issues.jboss.org/browse/RHPAM-2354
=> [RHPAM-2354] OutOfMemoryError on Datagrid cause issues on project import indexing

image.yaml
[KIECLOUD-328] required changes to build meta information for CPaaS
https://issues.jboss.org/browse/KIECLOUD-328
This PR is intended for RHDM / RHPAM version 7.5.0.
The PR for 7.5.1 is https://github.com/kiegroup/kie-cloud-operator/pull/276
=> [KIECLOUD-328] required changes to build meta information for CPaaS

README.md, getversion.go, hack/go-build.sh, pkg/controller/kieapp/deploy_ui_test.go
Added getversion.go ...
```bash
$ go run getversion.go 
Operator version is 1.2.1
Product version is 7.5.1
```
=> simplify versioning

config/7.5.0/common.yaml, config/7.5.1/common.yaml, config/7.6.0/common.yaml, deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml, deploy/role.yaml, pkg/components/components.go, pkg/controller/kieapp/deploy_ui.go
The reason for this is to further restrict the permissions we're allotting to our operator/product. This should allow us to offer dedicated users a way to deploy our operator/product at some point.
But also, this allows us to know what we really need. My initial testing has been successful.
=> move away from role wildcard rules

Gopkg.lock, Gopkg.toml, vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/common/GuiConstants.js, vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/OperatorWizard.js
Removed changes for Extension images for external DB from UI.
=> [RHPAM-2522] - Provide usable way of setting extensions image name and namespace for external DB driver in Operator UI

config/7.5.0/common.yaml, config/7.5.1/common.yaml, deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml, deploy/role.yaml
revert prior version product role configs so that upgrades occur correctly. use more permissive role for operator deployment until 7.5.x rolls off in operator 1.4.0.
/assign @bmozaffa @sutaakar 
=> [RHPAM-2602] fix configmap difference errors during 1.3.0 upgrades

config/7.5.1/common.yaml, config/7.6.1/common.yaml, deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml, deploy/catalog_resources/community/1.3.1/kiecloud-operator.1.3.1.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.3.1/businessautomation-operator.1.3.1.clusterserviceversion.yaml, deploy/role.yaml
revert prior version product role configs so that upgrades occur correctly. use more permissive role for operator deployment until 7.5.x rolls off in operator 1.4.0.
/assign @bmozaffa @sutaakar
Signed-off-by: tchughesiv tchughesiv@gmail.com
=> [RHPAM-2602] fix configmap difference errors during 1.3.1 upgrades

config/7.7.0/common.yaml
Align changes with Templates for bug fixing.
Related JIRA link:
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2634
Related PRs
https://github.com/jboss-container-images/jboss-kie-modules/pull/346
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/411
https://github.com/kiegroup/kie-cloud-operator/pull/343
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
=> [RHPAM-2634] Remote Server is lot from the controller after Kie Server scale down and scale up

deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml, deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml, deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml, deploy/catalog_resources/community/1.4.0/kiecloud-operator.1.4.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/1.4.0/businessautomation-operator.1.4.0.clusterserviceversion.yaml, tools/csv-gen/csv-gen.go, tools/util/marshaller.go
Fix https://issues.redhat.com/browse/RHPAM-2658
I have reproduced the issue and validated the fix on the following environment
```
Server Version: 4.4.0-0.nightly-2020-01-23-054055
Kubernetes Version: v1.17.1
```
```
oc create -f deploy/catalog_resources/redhat/1.4.0/businessautomation-operator.1.4.0.clusterserviceversion.yaml                                                                                                  
The ClusterServiceVersion "businessautomation-operator.1.4.0" is invalid: spec.customresourcedefinitions.owned.specDescriptors.value: Invalid value: "": spec.customresourcedefinitions.owned.specDescriptors.value in body must be of type byte: ""
```
=> [RHPAM-2658] Define value as byte

deploy/crds/kieapp.crd.yaml, deploy/ui/form.json, go.mod, go.sum, vendor/modules.txt
updated the Console form UI  w.r.t changes against RHPAM-2533 (build config changes in Operator for extensions image settings)
=> [RHPAM-2522] - Provide usable way of setting extensions image named namespace for external DB driver in Operator UI

config/7.7.0/common.yaml
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
Minor refactoring
PLEASE DO NOT MERGE TILL PREREQUISITE PRs MERGED
Related JIRAs
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2657
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2008
https://issues.redhat.com/browse/JBPM-8585
Prerequisite PRs
kiegroup/kie-wb-common#3139
kiegroup/droolsjbpm-integration#1995
Related PRs
jboss-container-images/jboss-kie-modules#352
https://github.com/jboss-container-images/rhdm-7-openshift-image/pull/329
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/414
=> [RHPAM-2657] KieServer Scale-Up-From-Zero lifecycle hooks logic broken

deploy/ui/form.json
CONTAINER_CORE_LIMIT and CONTAINER_MAX_MEMORY are removed
=> [BAPL-1507] - Add to OpenShift images property for JVM configurations

cmd/manager/main.go, pkg/apis/addtoscheme_app_apis.go
Create ServiceMonitor pointing to the metrics service.
=> [RHPAM-2694] Create ServiceMonitor for operator metrics

Makefile, deploy/crds/kieapp.crd.yaml, vendor/modules.txt
fixes this error seen in ocp4.3.5 when crd is installed -
```
[spec.version[v2].schema.openAPIV3Schema.type: Required value: must not be empty at the root, spec.version[v1].schema.openAPIV3Schema.type: Required value: must not be empty at the root]
```
adds printer columns -
```
$ oc get kieapp
NAME          VERSION   ENVIRONMENT   STATUS     AGE
rhpam-trial   7.8.0     rhpam-trial   Deployed   5m5s
test          7.8.0     rhpam-trial   Deployed   3m55s
```
[WIP] allow `oc explain` to work as expected as well??
https://github.com/kubernetes/kube-openapi/issues/97
https://itnext.io/understanding-kubectl-explain-9d703396cc8
=> fix crd schema

config/7.8.0/common.yaml, config/7.8.0/dbs/h2.yaml, config/7.8.0/dbs/mysql.yaml, config/7.8.0/dbs/postgresql.yaml, config/7.8.0/envs/rhdm-authoring-ha.yaml, config/7.8.0/envs/rhdm-authoring.yaml, config/7.8.0/envs/rhpam-authoring-ha.yaml, config/7.8.0/envs/rhpam-authoring.yaml, deploy/crds/kieapp.crd.yaml, deploy/examples/v2/server_mysql.yaml, deploy/examples/v2/server_postgresql.yaml, deploy/examples/v2/storage_class_name.yaml, pkg/apis/app/v2/kieapp_types.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/defaults/upgrade_test.go
in its current state... for HA envs, the `cr.spec.objects.console.storageClassName` setting is also used to configure the datagrid PVCs. 
=> [KIECLOUD-348] make storageClassName configurable

pkg/controller/initializer.go, pkg/controller/kieapp/deploy_ui.go, pkg/controller/kieapp/deploy_ui_test.go, pkg/controller/kieapp/shared/utils.go, tools/csv-gen/csv-gen.go
only ocp v4+ should use `service.beta.openshift.io/serving-cert-secret-name`... while earlier 3.x version should use the `alpha` annotation instead.
=> [RHPAM-2750] additional tests and service annotation fix

README.md, config/7.8.0/common.yaml, deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml, deploy/crds/kieapp.crd.yaml, go.sum, hack/go-fmt.sh, pkg/apis/app/v2/conversion.go, pkg/apis/app/v2/kieapp_types.go, pkg/apis/app/v2/status.go, pkg/apis/app/v2/zz_generated.deepcopy.go, pkg/components/components.go, pkg/controller/kieapp/defaults/auth.go, pkg/controller/kieapp/defaults/auth_test.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/defaults/merge_test.go, pkg/controller/kieapp/defaults/upgrade.go, pkg/controller/kieapp/defaults/upgrade_test.go, pkg/controller/kieapp/deploy_ui_test.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go, pkg/controller/kieapp/status/status.go, pkg/controller/kieapp/status/status_test.go, tools/csv-gen/csv-gen.go, vendor/modules.txt
results in a CR that looks like this:
```yaml
apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
annotations:
app.kiegroup.org: 7.8.0
creationTimestamp: '2020-04-28T20:23:51Z'
generation: 6
name: rhpam-trial
namespace: testtom
resourceVersion: '786037'
selfLink: /apis/app.kiegroup.org/v2/namespaces/testtom/kieapps/rhpam-trial
uid: fb5e4f4e-2d47-4e63-951c-857c100e22c5
spec:
commonConfig: {}
environment: rhpam-trial
objects:
console: {}
upgrades: {}
status:
conditions:
- lastTransitionTime: '2020-04-28T20:23:53Z'
status: 'True'
type: Provisioning
version: 7.8.0
- lastTransitionTime: '2020-04-28T20:23:55Z'
status: 'True'
type: Deployed
version: 7.8.0
consoleHost: 'https://rhpam-trial-rhpamcentr-testtom.apps-crc.testing'
deployments:
starting:
- rhpam-trial-rhpamcentr
stopped:
- …
```
=> [KIECLOUD-376] add generated section to KieApp status

pkg/apis/app/v2/status.go, pkg/apis/app/v2/zz_generated.deepcopy.go, pkg/controller/kieapp/defaults/auth.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/defaults/merge_test.go, pkg/controller/kieapp/defaults/upgrade.go, pkg/controller/kieapp/defaults/upgrade_test.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go, pkg/controller/kieapp/status/status.go, pkg/controller/kieapp/status/status_test.go
new `applied` status approach results in the following reconciled KieApp -
```yaml
apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
annotations:
app.kiegroup.org: 7.8.0
creationTimestamp: '2020-04-29T15:09:50Z'
generation: 23
name: prod
namespace: testtom
resourceVersion: '814170'
selfLink: /apis/app.kiegroup.org/v2/namespaces/testtom/kieapps/prod
uid: 00153694-dec9-4cf6-a3fe-8806de8afc83
spec:
commonConfig:
adminUser: testing
amqClusterPassword: this
environment: rhpam-production
objects:
console: {}
servers:
- deployments: 2
name: tom
- deployments: 1
upgrades:
enabled: true
status:
applied:
commonConfig:
adminPassword: r57mYMdn
adminUser: testing
amqClusterPassword: this
amqPassword: TdrrU816
applicationName: prod
dbPassword: xoJx7AFe
keyStorePassword: mgo4OQ7j
environment: …
```
=> [KIECLOUD-376] move to status.applied

deploy/catalog_resources/community/7.8/image-references, deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/7.8/image-references, deploy/operator.yaml, go.mod, pkg/components/components.go, pkg/controller/initializer.go, pkg/controller/kieapp/constants/constants.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/deploy_ui.go, pkg/controller/kieapp/deploy_ui_test.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/webconsole.go, tools/csv-gen/csv-gen.go, vendor/golang.org/x/mod/LICENSE, vendor/golang.org/x/mod/PATENTS, vendor/golang.org/x/mod/semver/semver.go, vendor/modules.txt
- `golang.org/x/mod/semver` for ocp and product version checks
- pim enabled only for product version 7.8+
- ocp 4.4 added
- oauth image tags changed to use `v4.x` format
- ConsoleLink and `inject-trusted-cabundle` ConfigMap only supported in OCP 4.2+
- ConsoleYAMLSamples only supported in OCP 4.3+
=> Switch to semver for product & ocp version checks

deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml, deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go
- ensure image tag used instead of sha when builds are involved
- ensure each serverset properly points to its own build/image
- fix issue where webhook passwds not being retained when multiple builds specified
- refactor server defaults & retention logic
=> [KIECLOUD-392] bypass sha for BC imagestreams

pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go
https://issues.redhat.com/browse/RHPAM-2746
@tchughesiv @spolti @jakubschwan
=> [RHPAM-2746 ] Set default JVM Max memory ratio to 80% in BA Operator

config/7.8.0/common.yaml, pkg/apis/app/v2/kieapp_types.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go
To follow up on KIECLOUD-394, KieApp Operator needs to suppress the creation and related configurations for persistent volume initially required by Business Central Monitoring Console.
Related JIRA:
https://issues.redhat.com/projects/KIECLOUD/issues/KIECLOUD-394
Related PR:
https://github.com/jboss-container-images/jboss-kie-modules/pull/370
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
=> [KIECLOUD-395] Enabling the new Simplified mode for Business Central Monitoring console for operator

config/7.8.0/common.yaml, deploy/crds/kieapp.crd.yaml, deploy/crs/v2/snippets/githooks.yaml, deploy/ui/form.json, pkg/apis/app/v2/kieapp_types.go, pkg/controller/kieapp/constants/constants.go, pkg/controller/kieapp/defaults/defaults_test.go
mounts a secret in BC at `/home/jboss/.ssh` with the following required files -
- id_rsa
- known_hosts
=> [RHPAM-2996] add ssh secret option to console object for githooks

pkg/controller/kieapp/constants/constants.go, pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go, pkg/controller/kieapp/shared/utils.go, pkg/controller/kieapp/shared/utils_test.go
This resolves an issue where when a generated keystore password changes, the keystore secret was not regenerated using the new password.
Without this change, affected kieserver and bc pods never successfully start due to an incorrect keystore pwd.
=> keystore patch

pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go
we need to ensure keystore secret isn't improperly replaced / removed.
we shouldn't reconcile the deployment with an incorrect or missing keystore secret.
=> requeue reconcile on keystore secret error

pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go
we need to ensure keystore secret isn't improperly replaced / removed.
we shouldn't reconcile the deployment with an incorrect or missing keystore secret.
=> [cherry-pick] requeue reconcile on keystore secret error

pkg/controller/kieapp/kieapp_controller.go, pkg/controller/kieapp/kieapp_controller_test.go
Signed-off-by: ruromero <rromerom@redhat.com>
Fix https://issues.redhat.com/browse/RHPAM-3055
=> [RHPAM-3055] Use CR name in the console links

README.md, deploy/crds/kieapp.crd.yaml, deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml, deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml, pkg/apis/app/v2/kieapp_types.go, tools/csv-gen/csv-gen.go
Leverage `urn:alm:descriptor:com.tectonic.ui:password` specDescriptor.
https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#8-password
=> [KIECLOUD-422] display admin user & pwd in Operator Hub

pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/upgrade_test.go
this is required now that we switched to status subresource.
=> upgrade fix: retain version from applied status

deploy/crds/kieapp.crd.yaml, deploy/ui/form.json, pkg/apis/app/v2/kieapp_types.go, pkg/apis/app/v2/zz_generated.deepcopy.go, pkg/controller/kieapp/constants/constants.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/test/crd_validation_test.go
Alongside the title JIRA this PR also solves the [BAPL-1766](https://issues.redhat.com/browse/BAPL-1766) as almost both were identical except for setting default value of `MaxMetaspaceSize`. Since that was a small thing I incorporated in this PR only
See: https://issues.redhat.com/browse/RHPAM-3245
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
=> [RHPAM-3245] - Change resource requirements for BC and KIE Server

config/7.9.1/common.yaml, config/7.9.1/envs/rhdm-trial.yaml, config/7.9.1/envs/rhpam-trial.yaml
Following the #533 the default resource limits set in the templates should be removed except  for the trial envs. In this PR the resource limits are moved from the common config to only for the trial envs
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
=> Remove default resource limits from template except for trial envs

pkg/controller/kieapp/deploy_ui.go
resolves - https://issues.redhat.com/browse/RHPAM-3296
will resolve the infinite reconciliation of console UI objects seen in this operator on 4.6.1 clusters. this is due to a new label that OLM is setting on objects a CSV owns... which is causing the operator to get stuck in a reconcile loop for the console UI deployment.
https://github.com/operator-framework/operator-lifecycle-manager/pull/1607
https://github.com/njhale/operator-lifecycle-manager/blob/162cbc091bdf22153e7c4e2a1b6e57df27407c02/pkg/controller/operators/adoption_controller.go#L196+L217
Operator repeatedly reconciles console objects owned by CSV...
```shell
{"level":"info","ts":"2020-11-06T19:32:09.064455626Z","logger":"kieapp.controller","msg":"No Custom Resource found named businessautomation-operator.7.9.1-dev-66g4svx9hl. …
```
=> [RHPAM-3296] console ownerRef fix for ocp 4.6.1+

deploy/crds/kieapp.crd.yaml, deploy/ui/form.json, pkg/apis/app/v2/kieapp_types.go, pkg/apis/app/v2/zz_generated.deepcopy.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, pkg/controller/kieapp/test/crd_validation_test.go
Reverting as the cct_modules append a `m` in the env
For more info See: https://github.com/jboss-openshift/cct_module/blob/0.39.0/jboss/container/java/jvm/bash/artifacts/opt/jboss/container/java/jvm/java-default-options#L157
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
=> Revert GcMaxMetaspaceSize CRD to accept the int

pkg/controller/kieapp/defaults/auth_test.go
After merging the KIECLOUD-480 [PR](https://github.com/kiegroup/kie-cloud-operator/pull/568) the unit test added were not getting executed. This PR fixes them and executes them from `go test`
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
=> [KIECLOUD-480] - Execute and Fix Unit Tests

config/7.11.0/common.yaml
https://github.com/kiegroup/kie-cloud-operator/pull/567 changes were causing an infinite reconcile loop in the operator due to missing field in new env vars.
=> fix reconcile errors due to RHPAM-3181 PR

deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml, deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml, deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml, hack/go-build-bundle.sh, pkg/controller/kieapp/deploy_ui_test.go, tools/csv-gen/csv-gen.go
until https://github.com/cekit/cekit/issues/700 is resolved, we'll name the csv files the same w/ each release. this will ensure only one cluster service version exists in each bundle built by osbs.
=> change csv file name to bypass cekit issue

config/7.10.1/envs/rhdm-authoring-ha.yaml, config/7.10.1/envs/rhpam-authoring-ha.yaml, deploy/olm-catalog/dev/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml, deploy/olm-catalog/prod/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml, deploy/olm-catalog/test/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml, deploy/operator.yaml, pkg/components/components.go, pkg/controller/kieapp/constants/constants.go, pkg/controller/kieapp/deploy_ui.go, pkg/controller/kieapp/deploy_ui_test.go
mostly around  signed serving certificates for services. i expect that code during console UI deployment may have been causing leftover token secrets to pile up for certain OSD customers.
this change moves from `service.alpha.openshift.io/serving-cert-secret-name` to `service.beta.openshift.io/serving-cert-secret-name` and removes the code potentially causing duplicate serving secrets.
=> [RHPAM-3504] remove several ocp3 specific lines and configs

deploy/ui/form.json, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go
[RHPAM-4075] - Kie repository persistence is disabled in rhpam-trial and the UI form re-instates the same.
https://issues.redhat.com/browse/RHPAM-4075
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
Thanks for submitting your Pull Request!
Please make sure your PR meets the following requirements:
=> [RHPAM-4075] - Kie repository persistence is disabled in rhpam-trial

deploy/crds/kieapp.crd.yaml, deploy/olm-catalog/dev/7.12.1-1/manifests/kieapp.crd.yaml, deploy/olm-catalog/prod/7.12.1-1/manifests/kieapp.crd.yaml, deploy/olm-catalog/test/7.12.1-1/manifests/kieapp.crd.yaml, deploy/ui/form.json, pkg/apis/app/v2/kieapp_types.go, pkg/apis/app/v2/zz_generated.deepcopy.go, pkg/controller/kieapp/defaults/defaults.go, pkg/controller/kieapp/defaults/defaults_test.go, rhpam-config/7.12.1/common.yaml
See: https://issues.redhat.com/browse/RHPAM-3528
=> [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image

deploy/ui/form.json
See:https://issues.redhat.com/browse/RHPAM-4239
=> [RHPAM-4239] KieExecutorMDB property in Operator UI use wrong name

deploy/ui/form.json
[RHPAM-4224] - Installer generates wrong Min/Max connection pool size in external DB configuration of CR.
https://issues.redhat.com/browse/RHPAM-4224
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
Thanks for submitting your Pull Request!
Please make sure your PR meets the following requirements:
=> [RHPAM-4224] - Installer generates wrong Min/Max connection pool size

image.yaml
Operator doesn't build with go-toolset 1.16.x
=> update go-toolset image to 1.17.7

deploy/ui/form.json
See: [RHPAM-4167](https://issues.redhat.com/browse/RHPAM-4167?focusedCommentId=20453745&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-20453745)
The change is following what suggested in [this example](https://github.com/RHsyseng/console-cr-form/blob/be2aa15abde0792dfb00cd4427a9f64fe6095f2f/test/examples/full-form.json#L137) of the Custom Resource Form Generation module.
=> [RHPAM-4167] Name of the property is wrongly set from console cr form

deploy/olm-catalog/dev/7.13.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml, deploy/olm-catalog/dev/7.13.1-2/manifests/kieapp.crd.yaml, deploy/olm-catalog/dev/7.13.1-2/metadata/annotations.yaml, deploy/olm-catalog/prod/7.13.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml, deploy/olm-catalog/prod/7.13.1-2/manifests/kieapp.crd.yaml, deploy/olm-catalog/prod/7.13.1-2/metadata/annotations.yaml, deploy/olm-catalog/test/7.13.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml, deploy/olm-catalog/test/7.13.1-2/manifests/kieapp.crd.yaml, deploy/olm-catalog/test/7.13.1-2/metadata/annotations.yaml, version/version.go
=> [KIECLOUD-656] - Prepare RHPAM branches for 7.13.2

image-prod.yaml, image.yaml
Bumping the go-toolset image tag to resolve CVE-2023-24540 html/template.
=> Bump go-toolset image to 1.19.9

image-prod.yaml, image.yaml
Another bump after #985 , 1.19.9 is vulnerable with
CVE-2023-39319
CVE-2023-39318
Both are fixed in 1.20.8, and here I am bumping to most recent 1.20 tag of go-toolset image.
=> Bump go-toolset image to 1.20.12

pkg/controller/kieapp/deploy_ui.go
Kieapp continuously remain in 'provisioning' state  after making any changes. They are not able to make any changes to applications due to this but their existing deployments seem to be working fine.
=> [DBACLD-168351] KIE app operators remain in the provisioning state
