internal/app/handler/handler_test.go
internal/pkg/defaults/defaults_test.go
internal/pkg/kieserver/objects_test.go
internal/pkg/rhpamcentr/objects_test.go

[KIECLOUD-7] Provide unit tests

[KIECLOUD-7] Provide unit tests

---

README.md
cmd/kie-cloud-operator/main.go
internal/app/handler/handler.go
internal/pkg/defaults/.packr/packr.go

[KIECLOUD-18] Create way to change logrus verbosity & replace all stdout with logrus statements
Optional `LOG_LEVEL` environment variable added

[KIECLOUD-18] Create way to change logrus verbosity & replace all stdout with logrus statements to stderr

---

.gitignore
pkg/apis/app/v1/kieapp_types.go
pkg/controller/kieapp/kieapp_controller.go

Refactor code to remove repeating blocks, and also to bubble up potential errors

[KIECLOUD-46] Refactor processing of OpenShift objects

---

config/common.yaml
config/envs/authoring-ha.yaml
config/envs/authoring.yaml
config/envs/production.yaml
config/envs/trial.yaml
config/testdata/envs/authoring-lite.yaml
config/testdata/envs/authoring-postgres-lite.yaml
config/testdata/expected/authoring-postgres.yaml
config/testdata/expected/authoring.yaml
deploy/crs/kieapp_authoring-ha.yaml
deploy/crs/kieapp_authoring.yaml
deploy/crs/kieapp_production.yaml
deploy/operator.yaml
deploy/role.yaml
deploy/role_binding.yaml

Using -
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
https://github.com/redhat-developer/yaml-language-server

yaml formatting

---

Gopkg.lock
pkg/controller/kieapp/kieapp_controller.go

[KIECLOUD-55]
- handle additional registry urls/locations for critical environment images

[KIECLOUD-55] ImageStreamTag enhancements

---

deploy/role.yaml

ServiceAccount cannot grant permissions it doesn't have

---

config/common.yaml
config/envs/authoring-ha.yaml
config/envs/authoring.yaml
config/envs/production.yaml
config/envs/trial.yaml
config/testdata/envs/authoring-lite.yaml
config/testdata/envs/authoring-postgres-lite.yaml
config/testdata/expected/authoring-postgres.yaml
config/testdata/expected/authoring.yaml
pkg/controller/kieapp/constants/constants.go

Fix https://issues.jboss.org/browse/KIECLOUD-51

[KIECLOUD-51] Align deployments with 7.2 templates

---

Gopkg.lock
config/common.yaml
config/envs/immutable-monitoring.yaml
config/envs/production-immutable.yaml
deploy/crs/kieapp_immutable_monitoring.yaml
deploy/crs/kieapp_production-immutable.yaml
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/defaults/merge_test.go

Combined immutable KIE server and monitoring env and CR into a single entity

[KIECLOUD-85] Fix remaining operator issues with the immutable-production environment

---

deploy/crds/kieapp_crd.yaml

Schema to validate the CR by CLI and help define expected input

[KIECLOUD-92] Provide OpenAPI v3 schema in the CRD

---

deploy/crds/kieapp.crd.yaml

crd cleanup

---

config/common.yaml
deploy/catalog_resources/kiecloud-operator.v0.1.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/kieapp_controller.go
pkg/controller/kieapp/kieapp_controller_test.go

- 7.3 config changes
- smartrouter keystore logic added
- imagestream fixes

[KIECLOUD-113] 7.3 changes

---

.gitignore
Makefile
README.md
build/Dockerfile.rhel
container.yaml
hack/go-build.sh
image.yaml
modules/business-automation-operator/install
modules/business-automation-operator/module.yaml

- pushes to dist-git and kicks off build in OSBS

[KIECLOUD-115] cekit for rhel builds

---

deploy/crds/kieapp.crd.yaml
pkg/apis/app/v1/kieapp_types.go
pkg/controller/kieapp/defaults/auth_test.go
pkg/controller/kieapp/test/crd_validation_test.go

- add crd validation tests for example CRs
- fix a couple types in crd

[KIECLOUD-124] crd validation fixes

---

deploy/role.yaml

Matched `deploy/role.yaml` to one used in CSV.

[KIECLOUD-132] role fixes for manual deployment

---

deploy/crds/kieapp.crd.yaml
deploy/examples/image_registry.yaml

[KIECLOUD-131] imageRegistry validation

---

deploy/catalog_resources/redhat/bundle.1.0.0.yaml
hack/catalog-redhat.sh

bundle file generation for OperatorHub

---

Makefile
README.md
hack/go-build.sh
image.yaml
modules/kie-cloud-operator/install

Adding logic to compile the operator binary during an OSBS image build.

[KIECLOUD-115] build improvements

---

pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults_test.go

As the Decision central and Business central are merged to one deliverable,
differentiated by configuration.

[1.0] [RHDM-861] Adjust Decision central probe URL

---

OWNERS

add tchughesiv to approvers

---

pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults_test.go

As the Decision central and Business central are merged to one deliverable,
differentiated by configuration.

[RHDM-861] Adjust Decision central probe URL

---

deploy/crds/kieapp.crd.yaml

remove crd comments

---

deploy/catalog_resources/redhat/catalog-source.yaml
hack/catalog-redhat.sh

CatalogSource file and generation for redhat catalog

---

config/common.yaml
config/envs/rhpam-production.yaml
pkg/controller/kieapp/defaults/defaults_test.go

Fix https://issues.jboss.org/browse/KIECLOUD-121

[KIECLOUD-121] Add KIE_SERVER_MODE default values

---

deploy/catalog_resources/redhat/catalog-source.yaml
deploy/crds/kieapp.crd.yaml
deploy/examples/common_config.yaml

add crd validation for commonConfig

---

deploy/catalog_resources/redhat/catalog-source.yaml
deploy/crds/kieapp.crd.yaml

remove required fields from for commonConfig validation

---

README.md
deploy/catalog_resources/community/kiecloud-operator.v1.0.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/businessautomation-operator.v1.0.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/catalog-source.yaml
deploy/operator.yaml

csv improvements

---

config/envs/rhdm-authoring.yaml
config/envs/rhdm-production-immutable.yaml

fixes KIECLOUD-152 & KIECLOUD-154
/assign @bmozaffa

[KIECLOUD-152] RHDM environment issues

---

config/envs/rhdm-authoring-ha.yaml
deploy/catalog_resources/community/kiecloud-operator.v1.0.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/businessautomation-operator.v1.0.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/catalog-source.yaml
pkg/apis/app/v1/kieapp_types.go
pkg/apis/app/v1/zz_generated.deepcopy.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/defaults/merge.go
pkg/controller/kieapp/kieapp_controller.go
pkg/controller/kieapp/watch.go

[KIECLOUD-155] rhdm authoring-ha fixes

---

config/dbs/mysql.yaml
config/dbs/postgresql.yaml

matching PRs -
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/257
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/251

[RHPAM-1970] add init containers for DB checks

---

config/common.yaml
deploy/catalog_resources/community/kiecloud-operator.v1.0.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/businessautomation-operator.v1.0.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/catalog-source.yaml
deploy/role.yaml

permissions cleanup

---

config/dbs/h2.yaml

[KIECLOUD-165] fix h2 db persistence

---

config/envs/rhdm-authoring-ha.yaml
config/envs/rhpam-authoring-ha.yaml
pkg/controller/kieapp/defaults/defaults_test.go

[KIECLOUD-168] rhpam authoring-ha fixes

---

config/dbs/h2.yaml
config/dbs/mysql.yaml
config/dbs/postgresql.yaml
config/envs/rhdm-authoring-ha.yaml
config/envs/rhpam-authoring-ha.yaml
deploy/catalog_resources/redhat/catalog-source.yaml
deploy/crds/kieapp.crd.yaml
pkg/apis/app/v1/kieapp_types.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

[KIECLOUD-174] new password fields for configuring DBs and AMQ

---

modules/kie-cloud-operator/install

minimal update for important vulnerabilities during rhel build

---

hack/go-fmt.sh
pkg/controller/kieapp/constants/constants.go

add simplify to go fmt

---

Gopkg.lock
Gopkg.toml
pkg/controller/kieapp/test/crd_validation_test.go
vendor/github.com/RHsyseng/operator-utils/.travis.yml
vendor/github.com/RHsyseng/operator-utils/Gopkg.lock
vendor/github.com/RHsyseng/operator-utils/README.md
vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema.go

Moved schema validation logic to operator library

Moved schema validation logic to operator library

---

README.md
deploy/catalog_resources/community/kiecloud-operator.1.0.0.clusterserviceversion.yaml
deploy/catalog_resources/community/kiecloud.package.yaml
deploy/catalog_resources/courier/bundle_dir/kieapp.crd.yaml
deploy/catalog_resources/courier/bundle_dir/kiecloud-operator.1.0.0.clusterserviceversion.yaml
deploy/catalog_resources/courier/bundle_dir/kiecloud.package.yaml
deploy/catalog_resources/courier/kiecloud-operatorsource.yaml
deploy/catalog_resources/redhat/businessautomation-operator.1.0.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/businessautomation.package.yaml
deploy/catalog_resources/redhat/catalog-source.yaml
hack/catalog-source.sh
hack/catalog.sh

Providing the required files and symbolic links to build and upload an operator bundle to OpenShift, and install the operator by creating an OperatorSource

OperatorSource and supporting files

---

image.yaml
modules/kie-cloud-operator/install

fix rhel build

---

Gopkg.lock
config/common.yaml
hack/catalog-redhat.sh
hack/catalog.sh
pkg/apis/app/v1/kieapp_types.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

[KIECLOUD-164] - Update the operator probes to match the new probes

---

pkg/controller/kieapp/constants/constants.go

increment image tag for PAM/DM 7.3.1

---

image.yaml
version/version.go

using 1.1 for rhpam73-operator image tag

increment version 1.0.1 for 7.3.1

---

Gopkg.lock
config/common.yaml
hack/catalog-redhat.sh
hack/catalog.sh
pkg/apis/app/v1/kieapp_types.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

Reverts kiegroup/kie-cloud-operator#121
@spolti fyi

Revert "[KIECLOUD-164] - Update the operator probes to match the new probes"

---

.gitignore
hack/go-build.sh
image.yaml
modules/kie-cloud-operator/install

cherry-picked commits https://github.com/kiegroup/kie-cloud-operator/commit/deb59bffcd703fd379c741cb138658078a5aca99 & https://github.com/kiegroup/kie-cloud-operator/commit/fc32e4eba835bc9721b2520771e7c45b57182484

cherry-pick 1.0.1 & rhel build fixes

---

config/common.yaml
deploy/catalog_resources/redhat/catalog-source.yaml
deploy/crds/kieapp.crd.yaml
pkg/apis/app/v1/kieapp_types.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

admin user field

---

deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.0.1/businessautomation-operator.1.0.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml

metadata improvements

---

deploy/catalog_resources/community/1.0.1/kiecloud-operator.1.0.1.clusterserviceversion.yaml
deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.0.1/businessautomation-operator.1.0.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml

Operator CSV installModes should have SingleNamespace support set to true

[KIECLOUD-193] Update CSV installModes

---

pkg/apis/app/v1/kieapp_types.go
pkg/controller/kieapp/kieapp_controller.go

The status of pods for a CR reported as arrays under each status name

[KIECLOUD-194] Deployment podStatuses faulty in OpenShift 4

---

.gitignore
Makefile
README.md
pkg/controller/kieapp/defaults/.packr/packr.go
pkg/controller/kieapp/defaults/defaults.go

packr vendoring fixes

---

Gopkg.lock
Gopkg.toml

add packr requirement to dep toml for builds

---

image.yaml
modules/kie-cloud-operator/install

go upgrade for rhel builds

---

deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
deploy/catalog_resources/community/1.1.0/kiecloud.1.1.0.package.yaml
deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.1.0/businessautomation.1.1.0.package.yaml
hack/go-build.sh

remove tech preview from rhel builds

---

pkg/controller/kieapp/kieapp_controller_test.go
pkg/controller/kieapp/test/mock_service.go

Unit tests to use mock k8s to validate podStatuses bug fix

[KIECLOUD-194] Test coverage for PR 148

---

Gopkg.lock
cmd/manager/main.go

@sutaakar image built and ready for testing at -
`quay.io/kiegroup/kie-cloud-operator:1.1`

[KIECLOUD-199] temporary disable ocp check for ocp 4.1

---

hack/go-build.sh

use tagged branch for builds

---

pkg/controller/kieapp/kieapp_controller_test.go
pkg/controller/kieapp/test/mock_service.go

Unit tests to use mock k8s to validate podStatuses bug fix

[KIECLOUD-194] Test coverage for PR148

---

Gopkg.toml

use specific revision instead of branch in dep

---

config/dbs/h2.yaml
pkg/controller/kieapp/defaults/defaults_test.go

See:
https://issues.jboss.org/browse/RHPAM-2125
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

[RHPAM-2125] Adding support for H2 Mixed Mode connection

---

config/common.yaml
config/envs/rhdm-authoring-ha.yaml
config/envs/rhdm-authoring.yaml
config/envs/rhdm-production-immutable.yaml
config/envs/rhdm-trial.yaml
config/envs/rhpam-authoring-ha.yaml
config/envs/rhpam-authoring.yaml
config/envs/rhpam-production-immutable.yaml
config/envs/rhpam-production.yaml
config/envs/rhpam-trial.yaml
deploy/crs/kieapp_rhpam_production.yaml
pkg/apis/app/v1/kieapp_types.go
pkg/apis/app/v1/zz_generated.deepcopy.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/defaults/merge_test.go
pkg/controller/kieapp/kieapp_controller.go
pkg/controller/kieapp/kieapp_controller_test.go

[KIECLOUD-219] allow smartRouter to be enabled from CR

---

config/common.yaml
config/dbs/h2.yaml
config/envs/rhdm-authoring-ha.yaml
config/envs/rhpam-authoring-ha.yaml
pkg/controller/kieapp/defaults/defaults_test.go

Please:
https://issues.jboss.org/browse/KIECLOUD-217
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

[KIECLOUD-217] - Kie data path standardization

---

Gopkg.lock
Gopkg.toml
deploy/ui/form.json
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/OperatorWizard.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/StepBuilder.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/element-component/field-factory/FieldFactory.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/element-component/field-factory/IntegerField.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js
vendor/github.com/RHsyseng/console-cr-form/test/examples/full-form.json
vendor/github.com/gophercloud/gophercloud/acceptance/openstack/networking/v2/extensions/portsbinding/portsbinding.go
vendor/github.com/gophercloud/gophercloud/acceptance/openstack/networking/v2/extensions/portsbinding/portsbinding_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/requests.go
vendor/github.com/prometheus/procfs/README.md
vendor/golang.org/x/oauth2/oauth2.go
vendor/golang.org/x/oauth2/oauth2_test.go
vendor/golang.org/x/sys/unix/types_aix.go
vendor/golang.org/x/sys/unix/ztypes_aix_ppc.go
vendor/golang.org/x/sys/unix/ztypes_aix_ppc64.go
vendor/golang.org/x/tools/internal/lsp/cache/check.go
vendor/golang.org/x/tools/internal/lsp/cache/view.go
vendor/golang.org/x/tools/internal/lsp/source/diagnostics.go

Operator UI update:
- Bug fix: Integer field support
- Smart Router as an optional
- Message dialog on view and deploy yaml
- Renamed process server to KIE server

Operator UI update

---

config/dbs/h2.yaml
pkg/controller/kieapp/defaults/defaults_test.go

[KIECLOUD-229] switch back to Rolling deployment strategy for kie server

---

config/common.yaml

In-sync Template changes pertaining RHPAM-2008 fix
Related PRs:
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/307
https://github.com/jboss-container-images/jboss-kie-modules/pull/251
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

[RHPAM-2008] HTTP 503 error is shown in Monitoring

---

modules/kie-cloud-operator/install

specify go version 1.11.5 in osbs builds

---

Gopkg.lock
Gopkg.toml
pkg/ui/serve.go
vendor/github.com/RHsyseng/console-cr-form/cmd/testwebapp.go
vendor/github.com/RHsyseng/console-cr-form/frontend/server.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/OperatorWizard.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/page-component/ReviewPage.js
vendor/github.com/RHsyseng/console-cr-form/pkg/web/configuration.go
vendor/github.com/RHsyseng/console-cr-form/pkg/web/http.go

Follow up on
Fix https://issues.jboss.org/browse/KIECLOUD-233

[KIECLOUD-233] Return error to UI when deployment fails

---

README.md
image.yaml

/assign @bmozaffa @errantepiphany 

cekit 3.1.0 changes

---

README.md
deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
deploy/catalog_resources/community/1.1.1/kiecloud.1.1.1.package.yaml
deploy/catalog_resources/courier/bundle_dir/1.1.1/kieapp.crd.yaml
deploy/catalog_resources/courier/bundle_dir/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
deploy/catalog_resources/courier/bundle_dir/1.1.1/kiecloud.1.1.1.package.yaml
deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.1.1/businessautomation.1.1.1.package.yaml
hack/go-build.sh
image.yaml
modules/kie-cloud-operator/install
pkg/controller/kieapp/constants/constants.go
version/version.go

version 1.1.1 / 7.4.1

---

Gopkg.lock
Gopkg.toml
pkg/ui/serve.go
vendor/github.com/RHsyseng/console-cr-form/cmd/testwebapp.go
vendor/github.com/RHsyseng/console-cr-form/pkg/web/http.go

Fix https://issues.jboss.org/browse/KIECLOUD-239
Depends on https://github.com/RHsyseng/console-cr-form/pull/78

[KIECLOUD-239] Log CR errors in debug level

---

pkg/controller/kieapp/watch.go

[KIECLOUD-231] watch/reconcile UI objects

---

Gopkg.lock
Gopkg.toml
deploy/ui/form.json
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/FormJsonLoader.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/OperatorWizard.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js
vendor/github.com/RHsyseng/console-cr-form/test/examples/full-form.json

Fix 
https://issues.jboss.org/browse/KIECLOUD-240
https://issues.jboss.org/browse/KIECLOUD-241

Align operator with latest UI changes

---

Gopkg.lock
Gopkg.toml
deploy/ui/form.json
vendor/github.com/RHsyseng/console-cr-form/cmd/testwebapp.go
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/FormJsonLoader.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/OperatorWizard.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js
vendor/github.com/RHsyseng/console-cr-form/pkg/web/http.go
vendor/github.com/RHsyseng/console-cr-form/test/examples/full-form.json

Cherry-pick - Align operator with latest UI changes

---

deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml

fix resourceNames across 1.1.x versions

---

config/common.yaml

[RHPAM-1387] - Allow set Smart router location to external URL in RHPAM

---

Gopkg.lock
Gopkg.toml
vendor/github.com/RHsyseng/console-cr-form/frontend/package-lock.json

fixed console js deps vulnerabilities

---

deploy/crs/kieapp_rhpam_production.yaml
deploy/examples/keystore-config.yaml
deploy/examples/server_config.yaml

/assign @sutaakar @bmozaffa @ruromero

deprecate smartRouter objects from example CRs

---

deploy/catalog_resources/community/1.1.0/kiecloud-operator.1.1.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.1.0/businessautomation-operator.1.1.0.clusterserviceversion.yaml

new capabilities annotation

---

modules/kie-cloud-operator/install

[KIECLOUD-278] remove go cache files post osbs build

---

pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/kieapp_controller_test.go

[KIECLOUD-284] Change patch upgrade default to false

---

modules/kie-cloud-operator/install

install latest available minor version of go-toolset for osbs builds

---

deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml

fix ba operator csv image tag

---

pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/kieapp_controller.go

[KIECLOUD-281] fix configmap version logic release-v1.1.x

---

pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/kieapp_controller.go

[KIECLOUD-281] fix configmap version logic

---

config/7.5.0/jms/activemq-jms-config.yaml
deploy/crds/kieapp.crd.yaml
deploy/crs/kieapp_rhpam_production-immutable-jms.yaml
pkg/apis/app/v1/kieapp_types.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/shared/utils.go

Follow up changes.
Need to expose the tcp-ssl port, 61617.

[KIECLOUD-122] - Enable JMS for RHDM and RHPAM images.

---

config/7.5.0/common.yaml

https://issues.jboss.org/browse/KIECLOUD-276
Signed-off-by: Karel Suta <ksuta@redhat.com>

[KIECLOUD-276] Adjust readiness probe parameters

---

config/7.4.0/common.yaml
config/7.4.1/common.yaml
config/7.5.0/common.yaml
deploy/crds/kieapp.crd.yaml
deploy/examples/v2/custom_images_registry.yaml
deploy/examples/v2/image_registry.yaml
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/test/crd_validation_test.go

[KIECLOUD-289] custom image/tag support for objects

---

image.yaml

[KIECLOUD-303] remove include_unpublished_pulp_repos from image.yaml

---

Gopkg.lock
Gopkg.toml
vendor/github.com/RHsyseng/console-cr-form/frontend/package-lock.json
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/OperatorWizard.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/OperatorWizardFooter.js
vendor/github.com/RHsyseng/console-cr-form/frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js
vendor/github.com/RHsyseng/console-cr-form/test/examples/full-form.json

Fix https://issues.jboss.org/browse/RHPAM-2245
Fix https://issues.jboss.org/browse/RHPAM-2246
Fix https://issues.jboss.org/browse/RHPAM-2247
Fix https://issues.jboss.org/browse/RHPAM-2248
/assign @swati-kale @bmozaffa 

[RHPAM-2245] UI Defects for 7.5

---

deploy/catalog_resources/community/1.1.1/kiecloud-operator.1.1.1.clusterserviceversion.yaml
deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.1.1/businessautomation-operator.1.1.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/deploy_ui.go
pkg/controller/kieapp/kieapp_controller.go

csv mods for seamless upgrades; use csv as owner for ui/cm objects

---

pkg/controller/kieapp/watch.go

change ownerhandler for cm & ui objects

---

config/7.4.0/envs/rhdm-authoring-ha.yaml
config/7.4.0/envs/rhpam-authoring-ha.yaml
config/7.4.1/envs/rhdm-authoring-ha.yaml
config/7.4.1/envs/rhpam-authoring-ha.yaml
config/7.5.0/envs/rhdm-authoring-ha.yaml
config/7.5.0/envs/rhpam-authoring-ha.yaml
pkg/controller/kieapp/kieapp_controller.go

[KIECLOUD-257] fix image name for scaledown controller

---

pkg/controller/kieapp/kieapp_controller.go

reconcile only secrets owned by CR

---

pkg/controller/kieapp/deploy_ui.go

[KIECLOUD-312] Console UI denies access to admins

---

tools/csv-gen/csv-gen.go

csv generation code cleanup

---

pkg/controller/kieapp/deploy_ui.go

change oauth SAR to allow edit role user access

---

deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
image.yaml
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

[KIECLOUD-332] 1.2.0 image naming convention changes

---

deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
image.yaml
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
tools/csv-gen/csv-gen.go

/assign @errantepiphany @bmozaffa 

[KIECLOUD-332] 1.2.1 image naming convention changes

---

image.yaml
modules/kie-cloud-operator/install

/assign @bmozaffa
This will force copy of linked crd instead of retaining a link that no longer exists.

fix nested bundle for release

---

modules/kie-cloud-operator/install

switch to rsync for manifests

---

deploy/ui/form.json

made corresponding changes in template at KIECloud operator side.

[RHPAM-2248] - Resources requests have incorrect name in CR YAML

---

Gopkg.lock
Gopkg.toml
pkg/controller/kieapp/deploy_ui.go
pkg/controller/kieapp/kieapp_controller.go
pkg/controller/kieapp/kieapp_controller_test.go
vendor/github.com/RHsyseng/operator-utils/Gopkg.lock
vendor/github.com/RHsyseng/operator-utils/Gopkg.toml
vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/defaults.go
vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/map.go
vendor/github.com/RHsyseng/operator-utils/pkg/resource/compare/types.go
vendor/github.com/RHsyseng/operator-utils/pkg/resource/read/reader.go
vendor/github.com/RHsyseng/operator-utils/pkg/resource/read/reader_test.go
vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer.go
vendor/github.com/RHsyseng/operator-utils/pkg/resource/write/writer_test.go

Use new write library from operator-utils
Conform to other refactors in operator-utils library

Refactor to use new operator-utils functions

---

deploy/ui/form.json

[RHPAM-2205] - Add AMQ support to Operator installer UI

---

config/7.6.0/common.yaml
config/7.6.0/dbs/postgresql.yaml
config/7.6.0/envs/rhdm-authoring-ha.yaml
config/7.6.0/envs/rhpam-authoring-ha.yaml
config/7.6.0/envs/rhpam-production.yaml
config/7.6.0/jms/activemq-jms-config.yaml
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/defaults/merge_test.go
pkg/controller/kieapp/defaults/upgrade_test.go

[RHPAM-2401] - Change strategy to type Rolling for other BA components

---

pkg/controller/kieapp/constants/constants.go

[RHPAM-2279/RHDM-1057] update amq and datagrid images

---

deploy/catalog_resources/community/1.1.0/kieapp.1.1.crd.yaml
deploy/catalog_resources/community/1.1.1/kieapp.1.1.crd.yaml
deploy/catalog_resources/redhat/1.1.0/kieapp.1.1.crd.yaml
deploy/catalog_resources/redhat/1.1.1/kieapp.1.1.crd.yaml

cleanup release crds

---

config/7.5.0/common.yaml
config/7.5.1/common.yaml
config/7.6.0/common.yaml

[KIECLOUD-343] allow product to get routes

---

config/7.5.0/common.yaml
config/7.5.1/common.yaml
config/7.6.0/common.yaml

[KIECLOUD-343] allow product to get pods

---

pkg/controller/kieapp/constants/constants.go

fix past micro imagetag

---

deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
deploy/role.yaml
pkg/components/components.go

[RHPAM-2550] fix expose metrics issue

---

deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
deploy/catalog_resources/community/1.3.1/kiecloud-operator.1.3.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.3.1/businessautomation-operator.1.3.1.clusterserviceversion.yaml
deploy/role.yaml
pkg/components/components.go

/hold
Signed-off-by: tchughesiv tchughesiv@gmail.com

[RHPAM-2550] cherry-picked - fix expose metrics issue

---

Gopkg.lock
Gopkg.toml
vendor/github.com/RHsyseng/console-cr-form/frontend/package-lock.json

[RHPAM-2249] fixes for console-cr-form packr files

---

image.yaml

use container-first go modules for OSBS

---

config/7.6.0/dbs/postgresql.yaml
pkg/controller/kieapp/defaults/merge_test.go

[RHPAM-2401-1] - QE review, db is not ba component

---

pkg/controller/kieapp/defaults/auth.go
pkg/controller/kieapp/defaults/auth_test.go
pkg/controller/kieapp/kieapp_controller.go
pkg/controller/kieapp/kieapp_controller_test.go

Fix https://issues.redhat.com/browse/RHPAM-2209

[RHPAM-2209] Fix failing scenarios

---

config/7.6.0/dbs/mysql.yaml
config/7.6.0/dbs/postgresql.yaml
config/7.6.1/dbs/mysql.yaml
config/7.6.1/dbs/postgresql.yaml

[RHPAM-2431] - Busybox dependency in Kieserver DeploymentConfig
See: https://issues.redhat.com/browse/RHPAM-2431
Signed-off-by: Mauricio Magnani mmagnani@redhat.com

[RHPAM-2431] - Busybox dependency in Kieserver DeploymentConfig

---

hack/go-mod.sh

mod CI script fixes

---

config/7.7.0/common.yaml
deploy/crds/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

Fix https://issues.redhat.com/browse/RHPAM-2175

[RHPAM-2175] Use only adminUser

---

hack/go-test.sh

add CI that catches prior version config changes

---

deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
deploy/catalog_resources/community/1.4.0/kiecloud-operator.1.4.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4.0/businessautomation-operator.1.4.0.clusterserviceversion.yaml
tools/csv-gen/csv-gen.go
tools/util/marshaller.go

Reverts kiegroup/kie-cloud-operator#349 given @madorn's findings... can address again once a solution is in place for ocp 4.4
https://github.com/kiegroup/kie-cloud-operator/pull/349#issuecomment-580415423

Revert "[RHPAM-2658] Define value as byte"

---

deploy/ui/form.json

[BAPL-1507] Add to OpenShift images property for JVM max memory ratio conf

---

deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
deploy/catalog_resources/community/1.2.1/kiecloud-operator.1.2.1.clusterserviceversion.yaml
deploy/catalog_resources/community/1.3.0/kiecloud-operator.1.3.0.clusterserviceversion.yaml
deploy/catalog_resources/community/1.4.0/kiecloud-operator.1.4.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.2.0/businessautomation-operator.1.2.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.3.0/businessautomation-operator.1.3.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4.0/businessautomation-operator.1.4.0.clusterserviceversion.yaml
tools/csv-gen/csv-gen.go

/assign @bmozaffa @ruromero @madorn
I've confirmed everything works as expected.

[RHPAM-2658] remove specDescripter value

---

hack/go-mod.sh

change CI vendoring in script

---

deploy/ui/form.json

 [RHPAM-2723] - LDAP Role recursion binds to wrong variable

---

config/7.7.0/dbs/external.yaml

Fix https://issues.redhat.com/browse/RHPAM-2726

[RHPAM-2726] PersistenceDS for external DB

---

config/7.7.0/dbs/external.yaml
deploy/ui/form.json

Merge master into release-1.4.x

---

config/7.7.0/common.yaml
deploy/crds/kieapp.crd.yaml
pkg/apis/app/v2/kieapp_types.go
pkg/apis/app/v2/zz_generated.deepcopy.go
pkg/controller/kieapp/defaults/defaults_test.go

[BAPL-1507] remove ContainerCoreLimit and ContainerMaxMemory
https://issues.redhat.com/browse/BAPL-1507

[BAPL-1507] remove ContainerCoreLimit and ContainerMaxMemory

---

README.md
deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
tools/csv-gen/csv-gen.go

add DIGESTS flag for make csv

---

deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
tools/csv-gen/csv-gen.go

[KIECLOUD-367] - Operator Hub catalog changes

---

deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
deploy/role.yaml
pkg/components/components.go

[KIECLOUD-373] remove all wildcard perm references

---

deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml

related to https://github.com/kiegroup/kie-cloud-operator/pull/365
/assign @ruromero @bmozaffa 

[RHPAM-2684] add cluster role to bundle

---

deploy/catalog_resources/community/1.4/image-references
deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4/image-references
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go

[RCM-78012] add image digests for 7.7.0 release & remove PIM image

---

image-metadata.yaml

change metadata package name

---

image.yaml
osbs-extra/gating.yaml

Signed-off-by: Alberto Morales Pérez <almorale@redhat.com>

BXMSPROD-708: add CVP checks configuration file

---

deploy/catalog_resources/community/1.4/image-references
deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4/image-references
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go

cherry-picking what was already pushed to release-v1.4.x branch.

[RHPAM-2803] add image digests for 7.7.0 release & remove PIM images

---

image-metadata.yaml
image.yaml

fix version in cekit files

---

pkg/controller/kieapp/deploy_ui.go
pkg/controller/kieapp/kieapp_controller.go
vendor/modules.txt

missed in https://github.com/kiegroup/kie-cloud-operator/pull/391

[KIECLOUD-373] fix console role perms

---

deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go

[KIECLOUD-378] Increase AMQ broker version to 7.6

---

deploy/catalog_resources/community/1.4/image-references
deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4/image-references
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go
tools/csv-gen/csv-gen.go

[RHPAM-2724] - Increase DataGrid 7.3 image tag version to 1.5

---

README.md
deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
tools/csv-gen/csv-gen.go

/hold
/assign @spolti 
Maybe using stage registry to populate digests accomplishes our needs for now? At least until ART automation is finished which will handle a lot of that for us?

[KIECLOUD-382] modify brew digest retrieval to use stage registry

---

go.mod
go.sum
vendor/github.com/RHsyseng/console-cr-form/pkg/web/form.go
vendor/github.com/RHsyseng/console-cr-form/pkg/web/http.go
vendor/modules.txt

new console module version

---

deploy/ui/form.json

add storageClassName to console

---

go.mod
go.sum
pkg/controller/initializer.go
vendor/github.com/RHsyseng/operator-utils/internal/platform/platform_versioner.go
vendor/github.com/RHsyseng/operator-utils/internal/platform/types.go
vendor/github.com/RHsyseng/operator-utils/pkg/utils/openshift/utils.go
vendor/modules.txt

Signed-off-by: Marco Yeung <myeung@redhat.com>
add logic for OCP version check before applying YAML Samples

VersionCheck for YAML Samples

---

deploy/ui/form.json

Console UI changes for PIM
@xiezhang7 , I have added the fields which you have requested for PIM. 
@tchughesiv ,Please do not merge it until PR consisting of CRD changes for PIM  gets merged.

[RHPAM-2497] - PIM - Operator console integration

---

config/7.7.1/common.yaml

add default apiversion to fieldRef

---

config/7.7.1/common.yaml

cherry-pick: add default apiversion to fieldRef

---

pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

With the new `Status.Applied` method, any passwords which we generate for the user must be carried forward between reconciles. Otherwise, an infinite loop occurs and reconciliation of objects never finishes.

fix jms and webhook password generation

---

pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

a continuation of https://github.com/kiegroup/kie-cloud-operator/pull/426
newly discovered bugs created from the new `status.applied` section

fix logic for webhook secrets

---

deploy/crds/kieapp.crd.yaml
deploy/ui/form.json

@jakubschwan @spolti @bmozaffa @tchughesiv

[RHPAM-2736] Add values type specification for JVM configuration in Operator

---

deploy/crs/v2/snippets/prior_version.yaml
tools/csv-gen/csv-gen.go

add a prior version snippet YAML sample

---

pkg/controller/kieapp/test/crd_validation_test.go

Test on jvm conf in Crd
@spolti @tchughesiv @jakubschwan @bmozaffa

[RHPAM-2735] Add JVM configuration tests to BA Operator

---

deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml
deploy/role.yaml
pkg/components/components.go

fix perms for servicemonitor creation

---

pkg/controller/kieapp/defaults/defaults_test.go

[RHDM-1352] kie-server immutable name unit test

---

pkg/components/components.go
pkg/controller/initializer.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/deploy_ui_test.go
tools/csv-gen/csv-gen.go

and remove "supported" verbiage.

rename ocp versions constant

---

deploy/catalog_resources/community/1.4/kiecloud-operator.1.4.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/1.4/businessautomation-operator.1.4.1.clusterserviceversion.yaml

7.7.1 image shas

---

config/7.8.0/pim/process-migration.yaml

Signed-off-by: ruromero <rromerom@redhat.com>
Fix https://issues.redhat.com/browse/RHPAM-2978

[RHPAM-2978] Fix PIM probes

---

config/7.8.0/pim/process-migration-trial.yaml
config/7.8.0/pim/process-migration.yaml
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

Signed-off-by: ruromero <rromerom@redhat.com>
Fix https://issues.redhat.com/browse/RHPAM-2998

[RHPAM-2998] Add http route for PIM in trial environment

---

deploy/ui/form.json
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

@jakubschwan @spolti @tchughesiv

[RHPAM-2752] Add default CPU limit for images to guarantee product performance

---

go.mod
go.sum
vendor/github.com/RHsyseng/operator-utils/internal/platform/platform_versioner.go
vendor/github.com/RHsyseng/operator-utils/pkg/utils/kubernetes/utils.go
vendor/modules.txt

support ocp 4.4

---

go.mod
go.sum
vendor/github.com/RHsyseng/operator-utils/internal/platform/platform_versioner.go
vendor/github.com/RHsyseng/operator-utils/pkg/utils/kubernetes/utils.go
vendor/modules.txt

[cherry-pick] support ocp 4.4

---

deploy/ui/form.json
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

Reverts kiegroup/kie-cloud-operator#443

Revert "[RHPAM-2752] Add default CPU limit for images to guarantee product performance"

---

.gitignore
Makefile

kie-cloud-operator.tar.gz .gitignore exception for release builds

---

pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/kieapp_controller.go
pkg/controller/kieapp/kieapp_controller_test.go
pkg/controller/kieapp/shared/utils.go
pkg/controller/kieapp/shared/utils_test.go

[cherry-pick] keystore patch

---

Makefile
hack/go-configs.sh
hack/go-test.sh

move check-configs to separate test

---

hack/go-configs.sh

fix configs job

---

deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.0.clusterserviceversion.yaml

7.8 metadata digests

---

deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
tools/csv-gen/csv-gen.go

https://bugzilla.redhat.com/show_bug.cgi?id=1861262

Add disconnected annotation

---

pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/kieapp_controller.go

change to strictly updating status, no longer the spec. also improve default jvm and resources logic.

reconcile cleanup

---

deploy/catalog_resources/community/7.9/image-references
deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.9/image-references
deploy/operator.yaml
go.sum
pkg/controller/kieapp/constants/constants.go
tools/csv-gen/csv-gen.go

[KIECLOUD-414] - Increase DataGrid 7.3 image tag version to 1.6

---

deploy/catalog_resources/community/7.9/image-references
deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.9/image-references
pkg/controller/kieapp/constants/constants.go
tools/csv-gen/csv-gen.go

remove no longer used datagrid73-openshift:1.3 from csv

---

deploy/catalog_resources/community/7.9/image-references
deploy/catalog_resources/community/7.9/kiecloud-operator.7.9.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.9/businessautomation-operator.7.9.0.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.9/image-references
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go
tools/csv-gen/csv-gen.go

[KIECLOUD-413] - Increase AMQ broker version to 7.7

---

deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.1.clusterserviceversion.yaml
deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.1.clusterserviceversion.yaml

generate 7.8.1 csv w/ digests

---

deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
deploy/role.yaml
pkg/components/components.go

add resource perms for metrics

---

deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
tools/csv-gen/csv-gen.go

fixes https://github.com/kiegroup/kie-cloud-operator/issues/512

revert admin user/pass from CSV descriptors

---

deploy/crds/kieapp.crd.v1beta1.yaml

format v1beta1 crd

---

deploy/crds/kieapp.crd.v1beta1.yaml

fix v1beta1 crd

---

README.md

readme changes for bundle test

---

image.yaml

OSBS fix - image build method

---

deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
go.sum

7.9.0 digests

---

image-bundle.yaml

only allow 7.9.0 in ocp4.6+

---

hack/go-mod.sh

check for missed vendor or generated code changes

add diff to CI

---

deploy/olm-catalog/dev/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.0/manifests/businessautomation-operator.7.9.0.clusterserviceversion.yaml

7.9.0CR2 digests

---

deploy/olm-catalog/dev/7.9.0-2/manifests/businessautomation-operator.7.9.0-2.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.9.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.9.0-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.9.0-2/manifests/businessautomation-operator.7.9.0-2.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.9.0-2/metadata/annotations.yaml
hack/go-build-bundle.sh
hack/go-build.sh
hack/go-csv.sh
tools/csv-gen/csv-gen.go

generate csv for 7.9.0 bug fix

---

pkg/controller/kieapp/deploy_ui.go
pkg/controller/kieapp/kieapp_controller.go
pkg/controller/kieapp/watch.go

UI reconcile improvements

---

cmd/manager/main.go
deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
deploy/role.yaml
pkg/components/components.go

https://issues.redhat.com/browse/KIECLOUD-463
Fix found here - https://github.com/operator-framework/operator-sdk/issues/1858#issuecomment-591721593

[KIECLOUD-463] fix metrics list & watch errors

---

cmd/manager/main.go
deploy/olm-catalog/dev/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
deploy/role.yaml
pkg/components/components.go

cherry-picked from https://github.com/kiegroup/kie-cloud-operator/pull/555

[KIECLOUD-463] cherry-pick to master

---

deploy/crds/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go

https://issues.redhat.com/browse/RHPAM-3056
Improved description
@spolti @jakubschwan @mramendi

[RHPAM-3056] Business Central remains "Container Creating" if missing known_hosts file in the githooks configuration

---

config/7.9.1/common.yaml
pkg/controller/kieapp/constants/constants.go

[RHPAM-3325] reconcile error due to mem conversion and startupProbe

---

deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml

add 7.9.1 digests

---

deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml

add 7.9.1 digests to master

---

deploy/olm-catalog/dev/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.0/manifests/businessautomation-operator.7.10.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go
tools/csv-gen/csv-gen.go

[KIECLOUD-474] increase amq version to 7.8

---

deploy/olm-catalog/dev/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.1/manifests/businessautomation-operator.7.9.1.clusterserviceversion.yaml

7.9.1 csv updates

---

config/7.10.0/common.yaml
config/7.10.0/envs/rhdm-authoring-ha.yaml
config/7.10.0/envs/rhdm-authoring.yaml
config/7.10.0/envs/rhpam-authoring-ha.yaml
config/7.10.0/envs/rhpam-authoring.yaml
deploy/crds/kieapp.crd.yaml
deploy/olm-catalog/dev/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

[RHPAM-3320] - Business Central PV size is not configurable in Operator

---

deploy/olm-catalog/dev/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml

generate 7.9.1-1 csvs w/ digest

---

hack/go-build-bundle.sh

fix image version for OSBS

---

deploy/olm-catalog/dev/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.9.1-1/manifests/businessautomation-operator.7.9.1-1.clusterserviceversion.yaml
hack/go-build-bundle.sh

cherry-pick: generate 7.9.1-1 csvs w/ digest

---

hack/go-build-bundle.sh

fix bundle build script

---

pkg/controller/kieapp/constants/constants.go

[RHPAM-3403] - Wrong default type of Console CPU request in Operator

---

pkg/controller/kieapp/constants/constants.go

@jakubschwan @spolti @tchughesiv

[RHPAM-3297] Update metering labels 7.10.x

---

pkg/controller/kieapp/constants/constants.go

See: https://issues.redhat.com/browse/RHPAM-3297
@tchughesiv @jakubschwan

[RHPAM-3297] Update metering labels - main

---

README.md
hack/go-build.sh

improve operator patch build logic

---

README.md
hack/go-build.sh

cherry-pick: improve operator patch build logic

---

deploy/olm-catalog/dev/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.10.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.10.0-2/metadata/annotations.yaml
deploy/olm-catalog/dev/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.10.0-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.10.0-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
pkg/controller/kieapp/defaults/defaults.go
version/version.go

[RHPAM-3471] cherry-pick: remove offending label & increment csv version 

---

deploy/olm-catalog/dev/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.10.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/module.yaml
deploy/olm-catalog/prod/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.0-2/manifests/businessautomation-operator.7.10.0-2.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.0-2/manifests/kieapp.crd.yaml
hack/go-build-bundle.sh
image-bundle.yaml
tools/csv-gen/csv-gen.go

use lookaside cache with local builds only

---

deploy/olm-catalog/dev/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.10.1-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/module.yaml
deploy/olm-catalog/prod/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.10.1-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.10.0-1/manifests/businessautomation-operator.7.10.0-1.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.1-1/manifests/kieapp.crd.yaml
hack/go-build-bundle.sh
image-bundle.yaml
tools/csv-gen/csv-gen.go

cherry-pick: only use lookaside cache with local builds

---

Makefile

ensure crd generates before csv

---

pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

See https://issues.redhat.com/browse/RHPAM-3481
@tchughesiv

[RHPAM-3481] Label for subcomp is wrongly set in Operator for images with digest

---

config/7.11.0/common.yaml
config/7.11.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/defaults/merge_test.go

See https://issues.redhat.com/browse/RHPAM-3181
@spolti @tchughesiv @jakubschwan

[RHPAM-3181] Update the openshift.PING to kubernetes.PING

---

deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/defaults/upgrade_test.go
pkg/controller/kieapp/status/status_test.go
tools/csv-gen/csv-gen.go
version/version.go

[KIECLOUD-495] reduce product version support to 2 per operator release

---

README.md

related to this issue https://github.com/cekit/cekit/issues/681
/hold

cekit upgrade for pushing bundle manifests via extra_dir

---

config/7.10.1/envs/rhdm-authoring-ha.yaml
config/7.10.1/envs/rhpam-authoring-ha.yaml
deploy/olm-catalog/dev/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.1-1/manifests/businessautomation-operator.7.10.1-1.clusterserviceversion.yaml
deploy/operator.yaml
pkg/components/components.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/deploy_ui.go
pkg/controller/kieapp/deploy_ui_test.go

Reverts kiegroup/kie-cloud-operator#618

Revert "[RHPAM-3504] remove several ocp3 specific lines and configs"

---

config/7.11.0/common.yaml
deploy/crds/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

See https://issues.redhat.com/browse/RHPAM-3330
Enable Kie Server Clustering on Openshift with same behaviour on-premise

[RHPAM-3330] Operator/Image support for Kie-Server Cluster support

---

deploy/olm-catalog/dev/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/operator.yaml
image-bundle.yaml
pkg/controller/kieapp/constants/constants.go

cleanup references to older ocp versions

---

pkg/controller/kieapp/shared/utils.go
pkg/controller/kieapp/shared/utils_test.go

[RHPAM-3476] add new unit test and fix func return

---

config/7.11.0/common.yaml
pkg/controller/kieapp/defaults/defaults_test.go

[RHPAM-3331] Operator for AMQ Streams (Kafka) integration

---

README.md
hack/go-build-bundle.sh

cekit 3.11 bundle build improvements

---

deploy/olm-catalog/dev/7.10.1-2/manifests/businessautomation-operator.7.10.1-2.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.10.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.10.1-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.10.1-2/manifests/businessautomation-operator.7.10.1-2.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.10.1-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.10.1-2/manifests/businessautomation-operator.7.10.1-2.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.10.1-2/metadata/annotations.yaml
version/version.go

7.10.1-2 bundle

---

deploy/olm-catalog/dev/7.10.1-2/manifests/businessautomation-operator.7.10.1-2.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.10.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.10.1-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.10.1-2/manifests/businessautomation-operator.7.10.1-2.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.10.1-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.1-2/manifests/businessautomation-operator.7.10.1-2.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.10.1-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.11.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
version/version.go

changes to account for 7.10.1-2 bundle

---

deploy/olm-catalog/dev/7.10.1-3/manifests/businessautomation-operator.7.10.1-3.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.10.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.10.1-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.10.1-3/manifests/businessautomation-operator.7.10.1-3.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.10.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.10.1-3/metadata/annotations.yaml
deploy/olm-catalog/test/7.10.1-3/manifests/businessautomation-operator.7.10.1-3.clusterserviceversion.yaml
deploy/olm-catalog/test/7.10.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.10.1-3/metadata/annotations.yaml
version/version.go

changes to account for 7.10.1-3 bundle

---

pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

[KIECLOUD-538] - Reconciliation loop if set CPU limit to 1000m

---

deploy/ui/form.json

Signed-off-by: Karel Suta <ksuta@redhat.com>

Fix JBPM Cluster typo

---

deploy/ui/form.json

Signed-off-by: Karel Suta <ksuta@redhat.com>

[7.11.x] Fix JBPM Cluster typo

---

deploy/ui/form.json
go.mod
go.sum
vendor/github.com/RHsyseng/console-cr-form/pkg/web/form.go
vendor/modules.txt

7.11.1
Update console-form-cr with latest fix

[RHPAM-3630] Update Console-form-cr with latest fixes

---

deploy/crs/v2/kieapp_rhdm_production-immutable-jms.yaml
deploy/crs/v2/kieapp_rhdm_production-immutable.yaml
deploy/crs/v2/kieapp_rhpam_production-immutable-jms.yaml
deploy/crs/v2/kieapp_rhpam_production-immutable.yaml
deploy/crs/v2/snippets/immutable_s2i.yaml
deploy/crs/v2/snippets/immutable_s2i_extra_buildconfig_envs.yaml
deploy/ui/form.json

See: https://issues.redhat.com/browse/KIECLOUD-542

[KIECLOUD-542] Conscious Language on KieCloud repos

---

deploy/olm-catalog/dev/7.11.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.11.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.11.0-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.11.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.11.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.11.0-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.11.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.11.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.11.0-2/metadata/annotations.yaml
version/version.go

- Move csv to next release tag.

[RHPAM-3763] - Endless updating loop in Kie operator

---

pkg/controller/kieapp/defaults/defaults_test.go

Signed-off-by: desmax74 mdessi@redhat.com
7.11.1
See: https://issues.redhat.com/browse/RHPAM-3640
@spolti

[RHPAM-3640] Configure Kafka JBPM Emitter from Operator -7.11.1

---

deploy/crds/kieapp.crd.yaml
deploy/olm-catalog/dev/7.11.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.11.1-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.11.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.11.1-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.11.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.11.1-1/manifests/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/defaults/defaults.go

[BXMSDOC-7448] - Improve jdbc extension image fields description

---

.gitignore
OWNERS
config/7.12.0/common.yaml
deploy/crds/kieapp.crd.yaml
deploy/crs/v2/snippets/server_persist_kie_repositories.yaml
deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go

See: https://issues.redhat.com/browse/RHPAM-3591

[RHPAM-3591] - Persist KIE Server maven and kie repositories

---

config/7.12.0/common.yaml
config/7.12.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
config/7.12.0/pim/process-migration.yaml
deploy/crds/kieapp.crd.yaml
deploy/crs/v2/snippets/controller_based_startup_strategy.yaml
deploy/crs/v2/snippets/custom-route-hostname.yaml
deploy/crs/v2/snippets/disable-ssl.yaml
deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/shared/utils.go

[KIECLOUD-569] - Route name is not exposed in operator CR

---

.gitignore
deploy/olm-catalog/dev/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.11.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.11.1-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.11.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.11.1-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.11.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.11.1-2/metadata/annotations.yaml
version/version.go

7.11.1-2 respin

---

deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults_test.go

[KIECLOUD-564] - 7.12 Checkpoint - Increase JDG version to 8.x
https://issues.redhat.com/browse/KIECLOUD-564
Signed-off-by: Achyut Madhusudan amadhusu@redhat.com
Thanks for submitting your Pull Request!
Please make sure your PR meets the following requirements:

[KIECLOUD-564] - 7.12 Checkpoint - Increased JDG version to 8.x

---

deploy/ui/form.json

See https://issues.redhat.com/browse/KIECLOUD-581
@spolti  @jakubschwan

[KIECLOUD-581] Console UI Broken

---

README.md
hack/go-build-bundle.sh

See:https://issues.redhat.com/browse/KIECLOUD-593

[KIECLOUD-593] Update BA Operator Docs about OLM

---

deploy/ui/form.json

See:https://issues.redhat.com/browse/RHPAM-3279
@spolti @jakubschwan

[rhpam-3279] 7.12.x Configure CORS automatically through a flag or environment variable

---

deploy/ui/form.json

See: https://issues.redhat.com/browse/RHPAM-4044
@spolti @jakubschwan

[RHPAM-4044] BA Operator UI generate startup strategy in wrong place

---

deploy/ui/form.json

See:https://issues.redhat.com/browse/RHPAM-3279
@spolti @jakubschwan

[RHPAM-3279] Configure CORS automatically through a flag or environment variable

---

deploy/olm-catalog/dev/7.11.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.11.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.11.1-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.11.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.11.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.11.1-3/metadata/annotations.yaml
deploy/olm-catalog/test/7.11.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.11.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.11.1-3/metadata/annotations.yaml
version/version.go

[CVE-2021-43527] - update bundle version due cve respin

---

deploy/olm-catalog/dev/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.11.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.11.1-2/metadata/annotations.yaml
deploy/olm-catalog/dev/7.11.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.11.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.11.1-3/metadata/annotations.yaml
deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.11.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.11.1-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.11.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.11.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.11.1-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.11.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.11.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.11.1-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.11.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.11.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.11.1-3/metadata/annotations.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
version/version.go

update 7.12.x branch with latest 7.11.1 respins

---

config/7.12.0/common.yaml
config/7.12.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
deploy/crds/kieapp.crd.yaml
deploy/crs/v2/snippets/auth_ldap_without_properties_file.yaml
deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/defaults/auth.go
pkg/controller/kieapp/defaults/auth_test.go

perspective
Ldap migration from legacy security subsystem to elytron

[RHPAM-4026] - [OpenShift] Users and Groups are not displayed in Admin

---

deploy/crds/kieapp.crd.yaml
deploy/crs/v2/snippets/auth_ldap_without_properties_file.yaml
deploy/olm-catalog/dev/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.12.1-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.1-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.1-1/manifests/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/defaults/auth.go
pkg/controller/kieapp/defaults/auth_test.go
rhpam-config/7.12.0/common.yaml
rhpam-config/7.12.0/dashbuilder/rhpam-standalone-dashbuilder.yaml
rhpam-config/7.12.1/common.yaml
rhpam-config/7.12.1/dashbuilder/rhpam-standalone-dashbuilder.yaml

Cherry-picks: https://github.com/kiegroup/kie-cloud-operator/pull/711

[RHPAM-4026] - [OpenShift] Users and Groups are not displayed in Admin perspective

---

deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go

See: https://issues.redhat.com/browse/RHPAM-4109

[RHPAM-4109] Cannot open created project - FileSystem Index fails - Nullpointer

---

deploy/olm-catalog/dev/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/role.yaml
pkg/components/components.go

See: https://issues.redhat.com/browse/RHPAM-4115

[RHPAM-4115] Missing routes/custom-host permision for BA Operator

---

image.yaml

[KIECLOUD-616] - uptade go-toolset image to 1.16

---

OWNERS

Updated Reviewers file to include davidesalerno

---

deploy/ui/form.json

See: https://issues.redhat.com/browse/RHPAM-4128

[RHPAM-4128] Fix label and description for routeHostname in Operator UI

---

deploy/olm-catalog/dev/7.12.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.12.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.12.0-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.12.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.0-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.12.0-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.0-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.0-2/metadata/annotations.yaml
version/version.go

operator in each namespace on the same OCP cluster
- bump csv version

[RHPAM-4158] - CRD conflicts when installing different version of

---

deploy/crds/kieapp.crd.v1beta1.yaml
deploy/crds/kieapp.crd.yaml
deploy/crs/v2/kieapp_rhdm_production-immutable-jms.yaml
deploy/crs/v2/kieapp_rhdm_production-immutable.yaml
deploy/crs/v2/snippets/immutable_deployment.yaml
deploy/crs/v2/snippets/immutable_s2i.yaml
deploy/crs/v2/snippets/immutable_s2i_extra_buildconfig_envs.yaml
deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/defaults/defaults_test.go

[KIECLOUD-628] - Update rhdm quickstarts references on operator

---

deploy/crds/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
pkg/apis/app/v2/kieapp_types.go

[RHPAM-4218] -  Matching the description in Operator UI and KieApp CRD for persistRepos
https://issues.redhat.com/browse/RHPAM-4218
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
Thanks for submitting your Pull Request!
Please make sure your PR meets the following requirements:

[RHPAM-4218] -  Matching the description in Operator UI and KieApp CRD for persistRepos

---

deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
deploy/operator.yaml
pkg/components/components.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/kieapp_controller.go
pkg/controller/kieapp/kieapp_controller_test.go

[KIECLOUD-629] - Update rhdm images reference on operator

---

deploy/crds/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/apis/app/v2/zz_generated.deepcopy.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
pkg/controller/kieapp/defaults/upgrade_test.go
rhpam-config/7.13.0/common.yaml

See: https://issues.redhat.com/browse/KIECLOUD-605

[KIECLOUD-605] In Operator use Kie Server's RHDM mode

---

deploy/crds/kieapp.crd.yaml
deploy/olm-catalog/dev/7.12.1-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.1-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.1-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/apis/app/v2/zz_generated.deepcopy.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
rhpam-config/7.12.1/common.yaml
rhpam-config/7.13.0/common.yaml

See:https://issues.redhat.com/browse/RHPAM-3528
(cherry picked from commit a0bd0e816adb67cc1660ea75ba8c1edb502170c5)

[RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image

---

pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
rhpam-config/7.13.0/common.yaml

[KIECLOUD-605] - In Operator use Kie Server's RHDM mode

---

deploy/crds/kieapp.crd.yaml
deploy/crs/v2/snippets/auth_secret.yaml
deploy/olm-catalog/dev/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/kieapp.crd.yaml
deploy/ui/form.json
pkg/apis/app/v2/kieapp_types.go
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
rhpam-config/7.13.0/common.yaml
rhpam-config/7.13.0/dashbuilder/rhpam-standalone-dashbuilder.yaml

See:https://issues.redhat.com/browse/RHPAM-4140
Signed-off-by: desmax74 mdessi@redhat.com

[RHPAM-4140] Hide adminPassword from Business automation operator

---

deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go

See: https://issues.redhat.com/browse/KIECLOUD-627
[DataGrid8 images](https://catalog.redhat.com/software/containers/datagrid/datagrid-8-rhel8/5d53e7b4d70cc5521d20ecea?tag=all)

[KIECLOUD-627] 7.13 Checkpoint - Increase JDG version to 8.3.3

---

deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/operator.yaml
version/version.go

bump bundle prior version to 7.12.1-2

---

deploy/olm-catalog/dev/7.12.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.12.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.12.1-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.12.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.1-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.12.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.1-2/metadata/annotations.yaml

Added 7.12.1-2 olm-catalog files

---

deploy/olm-catalog/dev/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/defaults/defaults.go

[KIECLOUD-606] - Remove from olm catalog manifest RHDM images references

---

deploy/olm-catalog/dev/7.12.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.12.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.12.1-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.12.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.1-3/metadata/annotations.yaml
deploy/olm-catalog/test/7.12.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.1-3/metadata/annotations.yaml
deploy/operator.yaml
version/version.go

Bump bundle version to 7.12.1-3

[7.12.x] bump bundle version to 7.12.1-3

---

deploy/olm-catalog/dev/7.12.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.12.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.12.1-3/metadata/annotations.yaml
deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.1-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.1-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.1-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.1-3/metadata/annotations.yaml
deploy/operator.yaml
version/version.go

bump bundle version to 7.12.1-3

[7.13.x] bump bundle version to 7.12.1-3

---

pkg/controller/kieapp/defaults/defaults.go

[RHPAM-4140] Hide adminPassword from Business automation operator kieapp instance

---

pkg/controller/kieapp/defaults/defaults.go

See: https://issues.redhat.com/browse/RHPAM-4140

[RHPAM-4140-7.13] Hide adminPassword from Business automation operator kieapp instance

---

deploy/olm-catalog/dev/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go

Reverted Infinispan to a working version
See: https://issues.redhat.com/browse/KIECLOUD-634

[KIECLOUD-634] Revert used RHDG version to 8.1

---

deploy/olm-catalog/dev/7.12.1-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.12.1-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.12.1-4/metadata/annotations.yaml
deploy/olm-catalog/prod/7.12.1-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.12.1-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.12.1-4/metadata/annotations.yaml
deploy/olm-catalog/test/7.12.1-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.12.1-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.12.1-4/metadata/annotations.yaml
version/version.go

Bump version to 7.12.1-4

---

deploy/cluster_role.yaml
deploy/cluster_role_binding.yaml
deploy/olm-catalog/dev/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/role_binding.yaml
deploy/service_account.yaml
pkg/components/components.go
tools/csv-gen/csv-gen.go

[KIECLOUD-640] - Fix naming of deploy yaml files

---

deploy/olm-catalog/dev/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/8.0.0-1/manifests/businessautomation-operator.clusterserviceversion.yaml
tools/csv-gen/csv-gen.go

add capabilities label to pass cvp tests

---

deploy/olm-catalog/dev/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/8.0.0-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
tools/csv-gen/csv-gen.go

fix typo, extra space

---

deploy/olm-catalog/dev/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go
pkg/controller/kieapp/kieapp_controller.go

See: https://issues.redhat.com/browse/RHPAM-4439

[RHPAM-4439] Vulnerable Version Of PostgreSQL Found

---

deploy/olm-catalog/dev/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.1-1/manifests/businessautomation-operator.clusterserviceversion.yaml
version/version.go

[KIECLOUD-654] - set correct prior version

---

deploy/olm-catalog/dev/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/kieapp_controller.go
pkg/controller/kieapp/kieapp_controller_test.go
tools/csv-gen/csv-gen.go

Signed-off-by: spolti <filippespolti@gmail.com>

[RHPAM-4437] - Gain All Capabilities Using Unshare

---

README.md
deploy/olm-catalog/dev/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.2-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/operator.yaml
pkg/controller/kieapp/constants/constants.go

See:https://issues.redhat.com/browse/RHPAM-4464

[RHPAM-4464]-PostgreSQL 13 Pod won't start due to version 10 data directory

---

deploy/olm-catalog/dev/7.13.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.1-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.1-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.1-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.1-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.1-2/metadata/annotations.yaml
version/version.go

bump bundle to 7.13.1-2

---

hack/build-osbs.sh
hack/go-build.sh
hack/image-osbs.patch

[KIECLOUD-660] Add nightly build for bamoe-operator

---

image-prod.yaml
modules/builder-prod/install
modules/builder-prod/module.yaml

This PR was created to retarget the changes to the _main_ branch, as a continuation of this PR (which was properly closed): 
**Related Pull Request**
* https://github.com/kiegroup/kie-cloud-operator/pull/850
* https://github.com/kiegroup/kie-cloud-operator/pull/853
* https://github.com/kiegroup/kie-cloud-operator/pull/854

[KIECLOUD][RHPAM-4609] Setting up Cachito tool.

---

image-prod.yaml
modules/builder-prod/install
modules/builder-prod/module.yaml

**Related Pull Requests**
* https://github.com/kiegroup/kie-cloud-operator/pull/853
* https://github.com/kiegroup/kie-cloud-operator/pull/854

[release-v7.13.x-blue][KIECLOUD][RHPAM-4609] Setting up Cachito tool.

---

deploy/olm-catalog/dev/7.13.2-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.2-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.2-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.2-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.2-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.2-3/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.2-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.2-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.2-3/metadata/annotations.yaml
version/version.go

Cherry-picks https://github.com/kiegroup/kie-cloud-operator/pull/872

[KIECLOUD-708] - Prepare RHPAM Operator for CVEs respin

---

deploy/olm-catalog/dev/7.13.3-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.3-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.3-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.3-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.3-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.3-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.3-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.3-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.3-2/metadata/annotations.yaml
version/version.go

Cherry-picks https://github.com/kiegroup/kie-cloud-operator/pull/893

[KIECLOUD-721] - Prepare RHPAM Operators for CVE respin

---

deploy/olm-catalog/dev/8.0.3-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/8.0.3-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/8.0.3-2/metadata/annotations.yaml
deploy/olm-catalog/prod/8.0.3-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/8.0.3-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/8.0.3-2/metadata/annotations.yaml
deploy/olm-catalog/test/8.0.3-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/8.0.3-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/8.0.3-2/metadata/annotations.yaml
version/version.go

Cherry-picks https://github.com/kiegroup/kie-cloud-operator/pull/897

[KIECLOUD-723] - Update RHPAM and BAMOE bundle due CVE respin

---

deploy/olm-catalog/dev/7.13.3-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.3-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.3-4/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.3-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.3-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.3-4/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.3-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.3-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.3-4/metadata/annotations.yaml
version/version.go

Cherry-picks https://github.com/kiegroup/kie-cloud-operator/pull/899

[KIECLOUD-725] - Update RHPAM and BAMOE bundle for CVE respin

---

pkg/controller/kieapp/defaults/defaults.go
pkg/controller/kieapp/defaults/defaults_test.go
rhpam-config/8.0.3/dbs/servers/external.yaml

Cherry-picks https://github.com/kiegroup/kie-cloud-operator/pull/903

[RHPAM-4704] - NoSuchMethodException: Method setURL not found

---

pkg/controller/kieapp/defaults/defaults_test.go
rhpam-config/8.0.3/dbs/servers/external.yaml

Cherry-picks https://github.com/kiegroup/kie-cloud-operator/pull/905

[RHPAM-4713] - Do not set URL envs if jdbcUrl property is not set

---

deploy/olm-catalog/dev/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/920
- https://github.com/kiegroup/kie-cloud-operator/pull/921

[release-v7.13.x-blue][KIECLOUD-732] add missing subscription for BAMOE 8.0.4-1 operator

---

deploy/olm-catalog/dev/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/8.0.4-1/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/920
- https://github.com/kiegroup/kie-cloud-operator/pull/921

[release-v7.13.x-blue-next][KIECLOUD-732] add missing subscription for BAMOE 8.0.4-1 operator

---

deploy/olm-catalog/dev/7.13.4-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.4-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.4-2/metadata/annotations.yaml
deploy/olm-catalog/dev/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.4-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.4-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.4-2/metadata/annotations.yaml
deploy/olm-catalog/prod/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.4-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.4-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.4-2/metadata/annotations.yaml
deploy/olm-catalog/test/manifests/kieapp.crd.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/922
- https://github.com/kiegroup/kie-cloud-operator/pull/923

[release-v7.13.x] Update RHPAM bundle for CVE respin

---

deploy/olm-catalog/dev/7.13.4-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.4-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.4-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.4-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.4-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.4-3/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.4-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.4-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.4-3/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/925
- https://github.com/kiegroup/kie-cloud-operator/pull/926

[release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2023-44487)

---

deploy/olm-catalog/dev/7.13.4-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.4-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.4-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.4-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.4-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.4-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.4-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.4-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.4-3/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-1/manifests/businessautomation-operator.clusterserviceversion.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/925
- https://github.com/kiegroup/kie-cloud-operator/pull/926

Update RHPAM bundle for CVE respin (CVE-2023-44487)

---

deploy/olm-catalog/dev/8.0.4-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/8.0.4-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/8.0.4-2/metadata/annotations.yaml
deploy/olm-catalog/prod/8.0.4-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/8.0.4-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/8.0.4-2/metadata/annotations.yaml
deploy/olm-catalog/test/8.0.4-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/8.0.4-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/8.0.4-2/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/932
- https://github.com/kiegroup/kie-cloud-operator/pull/933

[release-v7.13.x-blue] Update BAMOE bundle for CVE respin

---

deploy/olm-catalog/dev/8.0.4-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/8.0.4-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/8.0.4-2/metadata/annotations.yaml
deploy/olm-catalog/prod/8.0.4-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/8.0.4-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/8.0.4-2/metadata/annotations.yaml
deploy/olm-catalog/test/8.0.4-2/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/8.0.4-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/8.0.4-2/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/932
- https://github.com/kiegroup/kie-cloud-operator/pull/933

[release-v7.13.x-blue-next] Update BAMOE bundle for CVE respin

---

deploy/olm-catalog/dev/7.13.4-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.4-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.4-4/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.4-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.4-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.4-4/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.4-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.4-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.4-4/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/935
- https://github.com/kiegroup/kie-cloud-operator/pull/936

[release-v7.13.x] Update RHPAM bundle for CVE respin (Multiple OpenJDK CVEs)

---

deploy/olm-catalog/dev/7.13.4-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.4-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.4-4/metadata/annotations.yaml
deploy/olm-catalog/dev/7.13.5-1/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.4-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.4-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.4-4/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.4-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.4-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.4-4/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-1/manifests/businessautomation-operator.clusterserviceversion.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/935
- https://github.com/kiegroup/kie-cloud-operator/pull/936

Update RHPAM bundle for CVE respin (Multiple OpenJDK CVEs)

---

deploy/olm-catalog/dev/8.0.4-3/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/8.0.4-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/8.0.4-3/metadata/annotations.yaml
deploy/olm-catalog/prod/8.0.4-3/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/8.0.4-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/8.0.4-3/metadata/annotations.yaml
deploy/olm-catalog/test/8.0.4-3/manifests/bamoe-businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/8.0.4-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/8.0.4-3/metadata/annotations.yaml
version/version.go

related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/939
- https://github.com/kiegroup/kie-cloud-operator/pull/940

[release-v7.13.x-blue-next] Update BAMOE bundle for CVE respin (Multiple OpenJDK CVEs)

---

OWNERS

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/948
- https://github.com/kiegroup/kie-cloud-operator/pull/949

[release-v7.13.x-blue-next] add Abhishek and Rishiraj to OWNERS file

---

OWNERS

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/948
- https://github.com/kiegroup/kie-cloud-operator/pull/949

[release-v7.13.x-blue] add Abhishek and Rishiraj to OWNERS file

---

deploy/olm-catalog/dev/7.13.5-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-2/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-2/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-2/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-2/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-2/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/958
- https://github.com/kiegroup/kie-cloud-operator/pull/957

[release-v7.13.x] Update RHPAM bundle for CVE respin (PostgreSQL JDBC Driver CVE)

---

deploy/olm-catalog/dev/7.13.5-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-3/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-3/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/960
- https://github.com/kiegroup/kie-cloud-operator/pull/961

[release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2024-2961)

---

deploy/olm-catalog/dev/7.13.5-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-3/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-3/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-3/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-3/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-3/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/960
- https://github.com/kiegroup/kie-cloud-operator/pull/961

Update RHPAM bundle for CVE respin (CVE-2024-2961)

---

deploy/olm-catalog/dev/7.13.5-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-4/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-4/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-4/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/963
- https://github.com/kiegroup/kie-cloud-operator/pull/964

[release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2024-33599)

---

deploy/olm-catalog/dev/7.13.5-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-4/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-4/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-4/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-4/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-4/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/963
- https://github.com/kiegroup/kie-cloud-operator/pull/964

Update RHPAM bundle for CVE respin (CVE-2024-33599)

---

deploy/olm-catalog/dev/7.13.5-5/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-5/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-5/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-5/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-5/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-5/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-5/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-5/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-5/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/966
- https://github.com/kiegroup/kie-cloud-operator/pull/967

[release-v7.13.x] Update RHPAM bundle for CVE respin (Git and Less CVEs)

---

deploy/olm-catalog/dev/7.13.5-5/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-5/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-5/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-5/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-5/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-5/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-5/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-5/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-5/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/966
- https://github.com/kiegroup/kie-cloud-operator/pull/967

Update RHPAM bundle for CVE respin (Git and Less CVEs)

---

deploy/olm-catalog/dev/7.13.5-6/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-6/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-6/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-6/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-6/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-6/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-6/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-6/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-6/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/968
- https://github.com/kiegroup/kie-cloud-operator/pull/969

[release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2024-21147)

---

deploy/olm-catalog/dev/7.13.5-7/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-7/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-7/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-7/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-7/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-7/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-7/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-7/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-7/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/972
- https://github.com/kiegroup/kie-cloud-operator/pull/973

Update RHPAM bundle for CVE respin (CVE-2024-6345)

---

deploy/olm-catalog/dev/7.13.5-7/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-7/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-7/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-7/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-7/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-7/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-7/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-7/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-7/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/972
- https://github.com/kiegroup/kie-cloud-operator/pull/973

[release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2024-6345)

---

deploy/olm-catalog/dev/7.13.5-8/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-8/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-8/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-8/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-8/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-8/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-8/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-8/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-8/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/975
- https://github.com/kiegroup/kie-cloud-operator/pull/976

[release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2024-3596)

---

deploy/olm-catalog/dev/7.13.5-8/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-8/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-8/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-8/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-8/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-8/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-8/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-8/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-8/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/975
- https://github.com/kiegroup/kie-cloud-operator/pull/976

Update RHPAM bundle for CVE respin (CVE-2024-3596)

---

deploy/olm-catalog/dev/7.13.5-9/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-9/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-9/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-9/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-9/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-9/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-9/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-9/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-9/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/977
- https://github.com/kiegroup/kie-cloud-operator/pull/978

[release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2024-10963)

---

deploy/olm-catalog/dev/7.13.5-9/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-9/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-9/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-9/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-9/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-9/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-9/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-9/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-9/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/977
- https://github.com/kiegroup/kie-cloud-operator/pull/978

Update RHPAM bundle for CVE respin (CVE-2024-10963)

---

deploy/olm-catalog/dev/7.13.5-10/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-10/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-10/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-10/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-10/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-10/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-10/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-10/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-10/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/982
- https://github.com/kiegroup/kie-cloud-operator/pull/983

Update RHPAM bundle for CVE respin (CVE-2024-12085)

---

deploy/olm-catalog/dev/7.13.5-10/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-10/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-10/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-10/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-10/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-10/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-10/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-10/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-10/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/982
- https://github.com/kiegroup/kie-cloud-operator/pull/983

[release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2024-12085)

---

OWNERS

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/995
- https://github.com/kiegroup/kie-cloud-operator/pull/996

[release-v7.13.x] adding Saumya as part of OWNERS file

---

OWNERS

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/995
- https://github.com/kiegroup/kie-cloud-operator/pull/996

adding Saumya as part of OWNERS file

---

deploy/olm-catalog/dev/7.13.5-11/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/dev/7.13.5-11/manifests/kieapp.crd.yaml
deploy/olm-catalog/dev/7.13.5-11/metadata/annotations.yaml
deploy/olm-catalog/prod/7.13.5-11/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/prod/7.13.5-11/manifests/kieapp.crd.yaml
deploy/olm-catalog/prod/7.13.5-11/metadata/annotations.yaml
deploy/olm-catalog/test/7.13.5-11/manifests/businessautomation-operator.clusterserviceversion.yaml
deploy/olm-catalog/test/7.13.5-11/manifests/kieapp.crd.yaml
deploy/olm-catalog/test/7.13.5-11/metadata/annotations.yaml
version/version.go

Related PRs:
- https://github.com/kiegroup/kie-cloud-operator/pull/993
- https://github.com/kiegroup/kie-cloud-operator/pull/994

[release-v7.13.x] Update RHPAM bundle for CVE respin (CVE-2025-1244)
